templates:
  split_schemes:
    3j:
      split_categories:
        njets: ["==0", "==1", ">=2"]
      split_categories_binedges:
        njets: [-0.5, 0.5, 1.5, 22.5]
      correction_option:
        "==0": "smoothed"
        "==1": "smoothed"
        ">=2": "smoothed"
      bandwidth:
        "==0": 1.0
        "==1": 1.0
        ">=2": 1.0
    2j: &2j_split
      split_categories:
        njets: ["==0", ">=1"]
      split_categories_binedges:
        njets: [-0.5, 0.5, 22.5]
      correction_option:
        "==0": "smoothed"
        ">=1": "smoothed"
      bandwidth:
        "==0": 1.0
        ">=1": 1.0
  var_dependence_n_bins:
    QCD:
      equipopulated_binning_options: &QCD_var_dependence_n_bins
        var_dependence_n_bins: [15, 10]
    QCD_subleading:
      equipopulated_binning_options: &QCD_subleading_var_dependence_n_bins
        var_dependence_n_bins: [15, 10]
  variables:
    deltaR_ditaupair: &deltaR_ditaupair
      var_dependence: deltaR_ditaupair
      equipopulated_binning_options: &deltaR_ditaupair__eq_bin_opt
        variable_config:
          deltaR_ditaupair:
            min: 0.5
            max: 5.0
            rounding: 4
      correction_option: "smoothed"
    mass_1: &mass_1
      var_dependence: mass_1
      equipopulated_binning_options: &mass_1__eq_bin_opt
        variable_config:
          mass_1:
            min: 0.14
            max: 2.0
            rounding: 2
        add_left: [0.0]
      correction_option: "smoothed"
    mass_2: &mass_2
      var_dependence: mass_2
      equipopulated_binning_options: &mass_2__eq_bin_opt
        variable_config:
          mass_2:
            min: 0.14
            max: 2.0
            rounding: 2
        add_left: [0.0]
      correction_option: "smoothed"
    pt_1: &pt_1
      var_dependence: pt_1
      equipopulated_binning_options: &pt_1__eq_bin_opt
        variable_config:
          pt_1:
            min: 35.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    pt_2: &pt_2
      var_dependence: pt_2
      equipopulated_binning_options: &pt_2__eq_bin_opt
        variable_config:
          pt_2:
            min: 35.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    pt_tt: &pt_tt
      var_dependence: pt_tt
      equipopulated_binning_options: &pt_tt__eq_bin_opt
        variable_config:
          pt_tt:
            min: 0.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    eta_1: &eta_1
      var_dependence: eta_1
      equipopulated_binning_options: &eta_1__eq_bin_opt
        variable_config:
          eta_1:
            min: -2.3
            max: 2.3
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 0.2
    eta_2: &eta_2
      var_dependence: eta_2
      equipopulated_binning_options: &eta_2__eq_bin_opt
        variable_config:
          eta_2:
            min: -2.3
            max: 2.3
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 0.2
    jpt_1:
      var_dependence: jpt_1
      equipopulated_binning_options:
        variable_config:
          jpt_1:
            min: 30.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    jpt_2:
      var_dependence: jpt_2
      equipopulated_binning_options:
        variable_config:
          jpt_2:
            min: 30.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    met: &met
      var_dependence: met
      equipopulated_binning_options: &met__eq_bin_opt
        variable_config:
          met:
            min: 0.0
            max: 150.0
            rounding: 6
      correction_option: "smoothed"
      bandwidth: 1.0
    m_vis: &m_vis
      var_dependence: m_vis
      equipopulated_binning_options: &m_vis__eq_bin_opt
        variable_config:
          m_vis:
            min: 15.0
            max: 250.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    tau_decaymode_1: &tau_decaymode_1
      var_dependence: tau_decaymode_1
      correction_option: "binwise"
      bandwidth: 1.0
      var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
    tau_decaymode_2: &tau_decaymode_2
      var_dependence: tau_decaymode_2
      correction_option: "binwise"
      bandwidth: 1.0
      var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]


channel: tt
target_processes:
  QCD:
    non_closure:
      tau_decaymode_1:
        <<: [*tau_decaymode_1, *2j_split]
      mass_1:
        <<: [*mass_1, *2j_split]
        equipopulated_binning_options:
          <<: [*mass_1__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 0.2
        var_bins:
          "==0": [0.0, 0.14, 0.46, 0.54, 0.62, 0.69, 0.75, 0.82, 0.88, 0.95, 1.01, 1.08, 1.15, 1.22, 1.31, 1.42, 2.0]
          ">=1": [0.0, 0.14, 0.5, 0.62, 0.73, 0.83, 0.93, 1.03, 1.12, 1.23, 1.36, 2.0]
      eta_1:
        <<: [*eta_1, *2j_split]
        equipopulated_binning_options:
          <<: [*eta_1__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 0.5
        var_bins:
          "==0": [-2.3, -1.71, -1.33, -1.05, -0.79, -0.55, -0.3, -0.07, 0.15, 0.37, 0.6, 0.82, 1.04, 1.31, 1.68, 2.3]
          ">=1": [-2.3, -1.59, -1.11, -0.73, -0.35, 0.03, 0.4, 0.76, 1.11, 1.57, 2.3]
      pt_1:
        <<: [*pt_1, *2j_split]
        equipopulated_binning_options:
          <<: [*pt_1__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 5.0
        var_bins:
          "==0": [35.0, 44.07, 46.06, 47.77, 49.48, 51.15, 52.9, 54.75, 56.78, 59.05, 61.75, 65.02, 69.2, 74.96, 84.75, 150.0]
          ">=1": [35.0, 46.77, 50.74, 54.42, 58.46, 62.96, 68.0, 74.6, 83.6, 98.51, 150.0]
      # jpt_1:
      #   <<: [*jpt_1, *2j_split]
      #   equipopulated_binning_options:
      #     <<: [*jpt_1__eq_bin_opt, *QCD_var_dependence_n_bins]
      #   correction_option: ["skip", "smoothed"]
      #   bandwidth: 5.0
      #   var_bins:
      #     "==0": [30.0, 150.0]
      #     ">=1": [30.0, 32.99, 36.46, 40.88, 46.3, 52.47, 59.07, 67.97, 80.39, 100.8, 150.0]
      # jpt_2:
      #   <<: [*jpt_2, *2j_split]
      #   equipopulated_binning_options:
      #     <<: [*jpt_2__eq_bin_opt, *QCD_var_dependence_n_bins]
      #   correction_option: ["skip", "smoothed"]
      #   bandwidth: 5.0
      #   var_bins:
      #     "==0": [30.0, 150.0]
      #     ">=1": [30.0, 31.87, 34.18, 36.64, 39.99, 44.08, 49.69, 55.24, 63.47, 78.55, 150.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *2j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 1.0
        var_bins:
          "==0": [0.5, 2.8121, 2.9393, 3.0092, 3.059, 3.0982, 3.1307, 3.1668, 3.2161, 3.2755, 3.3524, 3.4476, 3.5687, 3.7354, 3.9934, 5.0]
          ">=1": [0.5, 1.6136, 2.2123, 2.5343, 2.7487, 2.9077, 3.0435, 3.1692, 3.366, 3.6977, 5.0]
      met:
        <<: [*met, *2j_split]
        equipopulated_binning_options:
          <<: [*met__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 10.0
        var_bins:
          "==0": [0.0, 6.173249, 8.927513, 11.357353, 13.589071, 15.747966, 17.824825, 20.078836, 22.466461, 25.150938, 27.951633, 31.451035, 35.802853, 41.835732, 52.428089, 150.0]
          ">=1": [0.0, 10.55864, 15.785311, 20.192743, 24.364447, 29.011282, 34.03801, 40.241814, 48.382557, 62.034786, 150.0]
      m_vis:
        <<: [*m_vis, *2j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 25.0
        var_bins:
          "==0": [15.0, 90.88, 96.13, 100.74, 105.09, 109.7, 114.43, 119.83, 125.79, 132.42, 140.24, 149.65, 161.84, 177.85, 201.93, 250.0]
          ">=1": [15.0, 76.25, 93.02, 104.29, 114.42, 125.07, 137.57, 152.05, 171.79, 200.39, 250.0]

    DR_SR:
      <<: [*pt_tt, *2j_split]
      equipopulated_binning_options:
        <<: [*pt_tt__eq_bin_opt, *QCD_var_dependence_n_bins]
      bandwidth: 20.0
      var_bins:
        "==0": [0.0, 5.8, 8.48, 10.76, 12.9, 15.0, 17.11, 19.32, 21.69, 24.31, 27.26, 30.7, 35.02, 40.92, 50.95, 150.0]
        ">=1": [0.0, 20.13, 28.43, 35.4, 42.02, 48.87, 56.59, 65.76, 78.09, 97.3, 150.0]

      SRlike_cuts:
        had_tau_id_vs_jet_2: (id_tau_vsJet_Medium_2 < 0.5)
      ARlike_cuts:
        had_tau_id_vs_jet_2: (id_tau_vsJet_Medium_2 < 0.5)
      AR_SR_cuts:
        tau_pair_sign: (q_1*q_2) < 0

      non_closure:
        tau_decaymode_1:
          <<: [*tau_decaymode_1, *2j_split]

  QCD_subleading:
    non_closure:
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *2j_split]
      mass_2:
        <<: [*mass_2, *2j_split]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 0.2
        var_bins:
          "==0": [0.0, 0.14, 0.44, 0.52, 0.59, 0.66, 0.72, 0.78, 0.84, 0.9, 0.96, 1.02, 1.09, 1.16, 1.26, 1.38, 2.0]
          ">=1": [0.0, 0.14, 0.5, 0.59, 0.69, 0.78, 0.87, 0.96, 1.06, 1.17, 1.32, 2.0]
      eta_2:
        <<: [*eta_2, *2j_split]
        equipopulated_binning_options:
          <<: [*eta_2__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 0.5
        var_bins:
          "==0": [-2.3, -1.75, -1.38, -1.1, -0.85, -0.61, -0.35, -0.1, 0.14, 0.38, 0.62, 0.87, 1.1, 1.36, 1.73, 2.3]
          ">=1": [-2.3, -1.57, -1.1, -0.72, -0.36, 0.02, 0.39, 0.75, 1.1, 1.55, 2.3]
      pt_2:
        <<: [*pt_2, *2j_split]
        equipopulated_binning_options:
          <<: [*pt_2__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 5.0
        var_bins:
          "==0": [35.0, 40.61, 41.27, 41.97, 42.73, 43.58, 44.48, 45.47, 46.64, 48.0, 49.62, 51.71, 54.41, 58.53, 66.22, 150.0]
          ">=1": [35.0, 41.07, 42.23, 43.6, 45.06, 46.93, 49.21, 52.38, 56.71, 65.16, 150.0]
      # jpt_1:
      #   <<: [*jpt_1, *2j_split]
      #   equipopulated_binning_options:
      #     <<: [*jpt_1__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
      #   correction_option: ["skip", "smoothed"]
      #   bandwidth: 5.0
      #   var_bins:
      #     "==0": [30.0, 150.0]
      #     ">=1": [30.0, 32.99, 36.46, 40.88, 46.3, 52.47, 59.07, 67.97, 80.39, 100.8, 150.0]
      # jpt_2:
      #   <<: [*jpt_2, *2j_split]
      #   equipopulated_binning_options:
      #     <<: [*jpt_2__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
      #   correction_option: ["skip", "smoothed"]
      #   bandwidth: 5.0
      #   var_bins:
      #     "==0": [30.0, 150.0]
      #     ">=1": [30.0, 31.87, 34.18, 36.64, 39.99, 44.08, 49.69, 55.24, 63.47, 78.55, 150.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *2j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 1.0
        var_bins:
          "==0": [0.5, 2.8121, 2.9393, 3.0092, 3.059, 3.0982, 3.1307, 3.1668, 3.2161, 3.2755, 3.3524, 3.4476, 3.5687, 3.7354, 3.9934, 5.0]
          ">=1": [0.5, 1.6136, 2.2123, 2.5343, 2.7487, 2.9077, 3.0435, 3.1692, 3.366, 3.6977, 5.0]
      met:
        <<: [*met, *2j_split]
        equipopulated_binning_options:
          <<: [*met__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 10.0
        var_bins:
          "==0": [0.0, 6.173249, 8.927513, 11.357353, 13.589071, 15.747966, 17.824825, 20.078836, 22.466461, 25.150938, 27.951633, 31.451035, 35.802853, 41.835732, 52.428089, 150.0]
          ">=1": [0.0, 10.55864, 15.785311, 20.192743, 24.364447, 29.011282, 34.03801, 40.241814, 48.382557, 62.034786, 150.0]
      m_vis:
        <<: [*m_vis, *2j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 25.0
        var_bins:
          "==0": [15.0, 90.88, 96.13, 100.74, 105.09, 109.7, 114.43, 119.83, 125.79, 132.42, 140.24, 149.65, 161.84, 177.85, 201.93, 250.0]
          ">=1": [15.0, 76.25, 93.02, 104.29, 114.42, 125.07, 137.57, 152.05, 171.79, 200.39, 250.0]

    DR_SR:
      <<: [*pt_tt, *2j_split]
      equipopulated_binning_options:
        <<: [*pt_tt__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
      bandwidth: 20.0
      var_bins:
        "==0": [0.0, 5.73, 8.29, 10.48, 12.55, 14.58, 16.65, 18.81, 21.13, 23.64, 26.51, 29.85, 34.05, 39.89, 49.7, 150.0]
        ">=1": [0.0, 19.5, 27.69, 34.51, 41.07, 48.12, 55.94, 65.62, 78.13, 97.68, 150.0]

      SRlike_cuts:
        had_tau_id_vs_jet_1: (id_tau_vsJet_Medium_1 < 0.5)
      ARlike_cuts:
        had_tau_id_vs_jet_1: (id_tau_vsJet_Medium_1 < 0.5)
      AR_SR_cuts:
        tau_pair_sign: (q_1*q_2) < 0

      non_closure:
        tau_decaymode_2:
          <<: [*tau_decaymode_2, *2j_split]
