channel: mt
target_processes:
  QCD:
    split_categories:
      njets: ["==0", "==1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [40, 25, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    var_dependence: pt_2
    # in case of individual splitting
    var_bins:
      "==0": [20.0, 20.37, 20.74, 21.1, 21.49, 21.87, 22.26, 22.68, 23.08, 23.49, 23.91, 24.36, 24.82, 25.29, 25.79, 26.32, 26.84, 27.35, 27.9, 28.49, 29.11, 29.72, 30.32, 30.99, 31.73, 32.48, 33.3, 34.2, 35.08, 36.05, 37.14, 38.37, 39.7, 41.26, 43.19, 45.23, 47.74, 51.24, 56.82, 66.69, 150.0]
      "==1": [20.0, 20.45, 20.91, 21.39, 21.9, 22.43, 23.02, 23.64, 24.31, 25.08, 25.85, 26.75, 27.65, 28.67, 29.76, 31.02, 32.39, 34.0, 35.81, 37.86, 40.43, 43.68, 48.29, 55.1, 71.01, 150.0]
      ">=2": [20.0, 21.36, 22.88, 24.63, 26.9, 29.56, 32.63, 36.69, 43.93, 58.38, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 20.0

  Wjets:
    split_categories:
      njets: ["==0", "==1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [40, 25, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    var_dependence: pt_2
    var_bins:
      "==0": [20.0, 20.28, 20.56, 20.87, 21.18, 21.49, 21.81, 22.12, 22.45, 22.8, 23.15, 23.53, 23.92, 24.32, 24.74, 25.16, 25.6, 26.06, 26.57, 27.08, 27.6, 28.18, 28.77, 29.43, 30.08, 30.79, 31.56, 32.39, 33.27, 34.25, 35.29, 36.47, 37.8, 39.33, 41.16, 43.44, 46.36, 50.38, 56.54, 67.8, 150.0]
      "==1": [20.0, 20.64, 21.33, 22.04, 22.79, 23.59, 24.41, 25.22, 26.12, 27.08, 28.11, 29.2, 30.35, 31.62, 33.01, 34.51, 36.19, 38.01, 40.18, 42.71, 46.1, 50.1, 55.75, 64.55, 79.72, 150.0]
      ">=2": [20.0, 22.01, 24.35, 26.99, 29.98, 33.56, 38.12, 44.1, 53.32, 71.09, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 20.0

  ttbar:
    split_categories:
      njets: ["<=1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [30, 30]

    SR_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Medium_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    AR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    SRlike_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Medium_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: '!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5))'

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: '!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5))'

    var_dependence: pt_2
    var_bins:
      "<=1": [20.0, 20.4, 20.87, 21.33, 21.82, 22.35, 22.94, 23.52, 24.15, 24.78, 25.44, 26.1, 26.83, 27.61, 28.41, 29.28, 30.12, 31.08, 32.22, 33.39, 34.8, 36.16, 37.78, 39.51, 41.68, 44.16, 47.11, 51.17, 57.84, 70.02, 150.0]
      ">=2": [20.0, 20.51, 20.96, 21.45, 22.03, 22.64, 23.25, 23.95, 24.7, 25.47, 26.22, 27.12, 27.99, 29.05, 30.07, 31.09, 32.09, 33.44, 34.74, 36.11, 37.88, 39.82, 42.31, 44.87, 48.27, 51.66, 55.87, 62.52, 74.31, 90.52, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 20.0

process_fractions:
  processes: ["QCD", "Wjets", "ttbar_J"]

  split_categories:
    njets: ["==0", "==1", ">=2"]
  split_categories_binedges:
    njets: [-0.5, 0.5, 1.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      mt_1:
        min: 0.0
        max: 70.0
        rounding: 2
    var_dependence_n_bins: [40, 25, 10]

  SR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: (iso_1 < 0.15)
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)
  AR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: (iso_1 < 0.15)
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

  var_dependence: mt_1
  var_bins:
    "==0": [0.0, 2.09, 4.21, 6.3, 8.44, 10.6, 12.76, 14.94, 17.1, 19.31, 21.49, 23.67, 25.79, 27.89, 29.97, 32.02, 34.0, 35.98, 37.9, 39.78, 41.62, 43.43, 45.17, 46.86, 48.53, 50.15, 51.72, 53.27, 54.75, 56.2, 57.62, 59.02, 60.37, 61.67, 62.94, 64.19, 65.39, 66.58, 67.75, 68.89, 70.0]
    "==1": [0.0, 3.16, 6.36, 9.65, 12.98, 16.34, 19.7, 23.1, 26.44, 29.77, 33.05, 36.19, 39.29, 42.25, 45.07, 47.82, 50.45, 52.95, 55.37, 57.7, 59.94, 62.07, 64.16, 66.16, 68.12, 70.0]
    ">=2": [0.0, 8.23, 16.45, 24.54, 32.43, 39.92, 46.86, 53.27, 59.27, 64.79, 70.0]
