# This is an example config containing information for the FF corrections

workdir_name: "08_2023_v8_boosted"
era: "2018"
channel: "et" # options are et, mt, tt

generate_json: True

target_process:
    QCD:
        non_closure:
            leading_lep_pt:
                var_dependence: "boosted_pt_1"
                var_bins: [120,140,160,180,200]
            lep_mt:
                var_dependence: "boosted_mt_1"
                var_bins: [0,10,20,30,40,50]
        DR_SR:
            var_dependence: "boosted_m_vis"
            var_bins: [20,40,60,80,100,120,140]
            SRlike_cuts:
                boostedtau_pair_sign: "same"
            ARlike_cuts:
                boostedtau_pair_sign: "same"
            AR_SR_cuts:
                boosted_deltaR_ditaupair: "<=0.8"
            non_closure:
                leading_lep_pt:
                    var_dependence: "boosted_pt_1"
                    var_bins: [120,140,160,180,200]

    Wjets:
        non_closure:
            leading_lep_pt:
                var_dependence: "boosted_pt_1"
                var_bins: [120,140,160,180,200]
        DR_SR:
            var_dependence: "boosted_m_vis"
            var_bins: [20,50,80,120,150]
            SRlike_cuts:
                boosted_lep_mt: ">=0.0"
            ARlike_cuts:
                boosted_lep_mt: ">=0.0"
            AR_SR_cuts:
                nbtag: ">=0"
                boosted_deltaR_ditaupair: "<=0.8"
            non_closure:
                leading_lep_pt:
                    var_dependence: "boosted_pt_1"
                    var_bins: [120,140,160,180,200]

    ttbar:
        non_closure:
            leading_lep_pt:
                var_dependence: "boosted_pt_1"
                var_bins: [120,140,160,180,200]
            m_vis:
                var_dependence: "boosted_m_vis"
                var_bins: [20,40,60,80,100,120,140,160]
