# This is an example config containing information for the FF corrections

workdir_name: "tt_05_2023_v4_btag"
era: "2018"
channel: "tt" # options are et, mt, tt

generate_json: True

target_process:
    QCD:
        non_closure:
            subleading_lep_pt:
                var_dependence: "pt_2"
                var_bins: [40,45,50,55,60,65,70,75,80,85,90,95,100,110,120]
            m_vis:
                var_dependence: "m_vis"
                var_bins: [0,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,200,250]
                
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,200,250]
            SRlike_cuts:
                had_tau_id_vs_jet_2: ["VVVLoose","Medium"]
            ARlike_cuts:
                had_tau_id_vs_jet_2: ["VVVLoose","Medium"]
            AR_SR_cuts:
                tau_pair_sign: "opposite" 
            non_closure:
                subleading_lep_pt:
                    var_dependence: "pt_2"
                    var_bins: [40,45,50,55,60,65,70,75,80,85,90,95,100,110,120]

    QCD_subleading:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [40,45,50,55,60,65,70,75,80,85,90,95,100,110,120]
            m_vis:
                var_dependence: "m_vis"
                var_bins: [0,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,200,250]

        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,200,250]
            SRlike_cuts:
                had_tau_id_vs_jet_1: ["VVVLoose","Medium"]
            ARlike_cuts:
                had_tau_id_vs_jet_1: ["VVVLoose","Medium"]
            AR_SR_cuts:
                tau_pair_sign: "opposite" 
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [40,45,50,55,60,65,70,75,80,85,90,95,100,110,120]