# This is an example config containing information for the FF corrections

workdir_name: "09_2023_test_boosted"
era: "2018"
channel: "mt" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [55,60,65,70,75,80,85,90,95,100]
            lep_mt:
                var_dependence: "mt_1"
                var_bins: [0,5,10,15,20,25,30,35,40,45,50]
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,10,20,30,40,50,60,70]
            SRlike_cuts:
                tau_pair_sign: "(q_1*q_2) > 0" 
            ARlike_cuts:
                tau_pair_sign: "(q_1*q_2) > 0" 
            AR_SR_cuts:
                deltaR_ditaupair: "deltaR_ditaupair <= 0.8"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [55,60,65,70,75,80,85,90,95,100]

    Wjets:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [55,60,65,70,75,80,85,90,95,100]
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,20,40,60,80,120]
            SRlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            ARlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            AR_SR_cuts:
                nbtag: "nbtag >= 0"
                deltaR_ditaupair: "deltaR_ditaupair <= 0.8"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [55,60,65,70,75,80,85,90,95,100]

    ttbar:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [55,60,65,70,75,80,85,90,95,100]
            m_vis:
                var_dependence: "m_vis"
                var_bins: [0,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
