# This is an example config containing information for the FF corrections

workdir_name: "05_2024_v1"
era: "2018"
channel: "mt" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
                
            lep_iso:
                var_dependence: "iso_1"
                var_bins: [0.,0.01,0.05,0.1,0.15,0.2,0.25,0.31]
                SRlike_cuts:
                    lep_iso: "iso_1 >= 0.0"
                ARlike_cuts:
                    lep_iso: "iso_1 >= 0.0"
                
        DR_SR:
            # var_dependence: "m_vis"
            # var_bins: [0,50,75,100,120,140,160,180,250]
            var_dependence: "deltaR_ditaupair"
            var_bins: [2.0,2.2,2.4,2.6,2.8,3.0,3.2,3.4,3.6,3.8]
            SRlike_cuts:
                lep_iso: "(iso_1 >= 0.15) && (iso_1 < 0.3)"
                m_vis: "m_vis > 80."
            ARlike_cuts:
                lep_iso: "(iso_1 >= 0.15) && (iso_1 < 0.3)"
                m_vis: "m_vis > 80."
                # deltaR_ditaupair: "deltaR_ditaupair > 3.2"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0" 
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [25,30,35,40,45,50,55,60,65,70,80,100]

    Wjets:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
            
            lep_iso:
                var_dependence: "iso_1"
                var_bins: [0.,0.01,0.05,0.1,0.15,0.2,0.25,0.31]
                SRlike_cuts:
                    lep_iso: "iso_1 >= 0.0"
                ARlike_cuts:
                    lep_iso: "iso_1 >= 0.0"
                
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,40,70,100,140,180,250]
            SRlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            ARlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            AR_SR_cuts:
                nbtag: "(nbtag >= 1) || (fj_Xbb_pt > 200)"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]

    ttbar:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
