# This is an example config containing information for the FF corrections

workdir_name: "05_2024_v1_boosted"
era: "2018"
channel: "et" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [40,60,80,100,120,140,170,210]
            lep_mt:
                var_dependence: "mt_1"
                var_bins: [0,5,10,15,20,25,30,50]
        
        DR_SR:
            # var_dependence: "m_vis"
            # var_bins: [0,20,40,60,80]
            var_dependence: "deltaR_ditaupair"
            var_bins: [0.1,0.4,0.5,0.6,0.7,0.8]
            SRlike_cuts:
                tau_pair_sign: "(q_1*q_2) > 0"
            ARlike_cuts:
                tau_pair_sign: "(q_1*q_2) > 0"
            AR_SR_cuts:
                deltaR_ditaupair: "deltaR_ditaupair <= 0.8"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [40,60,80,100,120,140,170,210]

    Wjets:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [40,60,80,100,120,135,150,165,180,210]
        
        DR_SR:
            # var_dependence: "m_vis"
            # var_bins: [0,20,50,80,120]
            var_dependence: "deltaR_ditaupair"
            var_bins: [0.1,0.4,0.5,0.6,0.7,0.8]
            SRlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            ARlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            AR_SR_cuts:
                # nbtag: "nbtag >= 0"
                deltaR_ditaupair: "deltaR_ditaupair <= 0.8"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [40,60,80,100,120,135,150,165,180,210]

    ttbar:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [40,60,80,100,120,135,150,165,180,210]
            m_vis:
                var_dependence: "m_vis"
                var_bins: [0,20,40,60,80,120]
