# This is an example config containing information for the FF corrections

workdir_name: "08_2024_v1"
era: "2018"
channel: "tt" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            subleading_lep_pt:
                var_dependence: "pt_2"
                var_bins: [40,50,60,70,100]
            leading_lep_mass:
                var_dependence: "mass_1"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]
            # m_vis:
            #     var_dependence: "m_vis"
            #     var_bins: [0,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,200,250]
                
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,50,70,90,110,130,150,170,200,250]
            SRlike_cuts:
                had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
            ARlike_cuts:
                had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0"
            non_closure:
                subleading_lep_pt:
                    var_dependence: "pt_2"
                    var_bins: [40,50,60,70,80,100]

    QCD_subleading:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [40,55,70,85,100,120]
            subleading_lep_mass:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]
            # m_vis:
            #     var_dependence: "m_vis"
            #     var_bins: [0,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,200,250]

        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,50,70,90,110,130,150,170,200,250]
            SRlike_cuts:
                had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            ARlike_cuts:
                had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [40,50,60,70,80,90,100,120]

    ttbar:
        non_closure:
            subleading_lep_pt:
                var_dependence: "pt_2"
                var_bins: [40,50,60,70,80,100]
            leading_lep_mass:
                var_dependence: "mass_1"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]
    
    ttbar_subleading:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [40,50,60,70,80,90,100]
            subleading_lep_mass:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]