# This is an example config containing information for the FF corrections

workdir_name: "09_2023_test_boosted"
era: "2018"
channel: "et" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [120,140,160,180,200]
            lep_mt:
                var_dependence: "mt_1"
                var_bins: [0,10,20,30,40,50]
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [20,40,60,80,100,120,140]
            SRlike_cuts:
                tau_pair_sign: "(q_1*q_2) > 0"
            ARlike_cuts:
                tau_pair_sign: "(q_1*q_2) > 0"
            AR_SR_cuts:
                deltaR_ditaupair: "deltaR_ditaupair <= 0.8"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [120,140,160,180,200]

    Wjets:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [120,140,160,180,200]
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [20,50,80,120,150]
            SRlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            ARlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            AR_SR_cuts:
                nbtag: "nbtag >= 0"
                deltaR_ditaupair: "deltaR_ditaupair <= 0.8"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [120,140,160,180,200]

    ttbar:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [120,140,160,180,200]
            m_vis:
                var_dependence: "m_vis"
                var_bins: [20,40,60,80,100,120,140,160]
