# This is an example config containing information for the FF calculation

file_path: "/ceph/nshadskiy/FFmethod/05_2024_v1"
era: "2018"
channel: "tt" # options are et, mt, tt
tree: "ntuple"

workdir_name: "05_2024_v1"

use_embedding: True

target_processes: 
    QCD: 
        split_categories: 
            njets: 
                # - "==0" 
                - "<=1"
                - ">=2"
        split_categories_binedges:
            njets: [-0.5,1.5,2.5]

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"
        
        var_dependence: "pt_1"
        var_bins: [40,50,60,70,80,90,100]

    QCD_subleading: 
        split_categories: 
            njets: 
                # - "==0" 
                - "<=1"
                - ">=2"
        split_categories_binedges:
            njets: [-0.5,1.5,2.5]

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"
        
        var_dependence: "pt_2"
        var_bins: [40,50,60,70,80,100]

    # ttbar: 
    #     split_categories: 
    #         njets:  
    #             - "<=1"
    #             - ">=2"
    #     split_categories_binedges:
    #         njets: [-0.5,1.5,2.5]

    #     SR_cuts:
    #         tau_pair_sign: "(q_1*q_2) < 0" 
    #         nbtag: "nbtag >= 1"
    #         no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
    #         had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
    #         had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"

    #     AR_cuts:
    #         tau_pair_sign: "(q_1*q_2) < 0" 
    #         nbtag: "nbtag >= 1"
    #         no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
    #         had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
    #         had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"

    #     SRlike_cuts:
    #         tau_pair_sign: "(q_1*q_2) < 0" 
    #         nbtag: "nbtag >= 1"
    #         no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
    #         had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
    #         had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            
    #     ARlike_cuts:
    #         tau_pair_sign: "(q_1*q_2) < 0" 
    #         nbtag: "nbtag >= 1"
    #         no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
    #         had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
    #         had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
        
    #     var_dependence: "pt_2"
    #     var_bins: [40,44,52,70,100]

process_fractions:
    processes: ["QCD", "Wjets", "ttbar_J"]

    split_categories:
        nbtag:
            - "==0"
            - "==1"
            - ">=2"
    split_categories_binedges:
        nbtag: [-0.5,0.5,1.5,2.5]

    AR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
        had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
        had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
        bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

    SR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
        had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
        had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
        bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

    var_dependence: "m_vis"
    var_bins: [0,30,40,50,60,70,80,90,100,110,120,130,140,150]