# This is an example config containing information for the FF calculation

file_path: "/ceph/nshadskiy/FFmethod/09_2023_test"
era: "2018"
channel: "tt" # options are et, mt, tt
tree: "ntuple"

workdir_name: "09_2023_test"

use_embedding: True

target_processes: 
    QCD: 
        split_categories: 
            njets: 
                - "==0" 
                - "==1"
                - ">=2"
        split_categories_binedges:
            njets: [-0.5,0.5,1.5,2.5]

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"

        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
            had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
        
        var_dependence: "pt_1"
        var_bins: [40,42.5,45,50,55,60,65,100]

    QCD_subleading: 
        split_categories: 
            njets: 
                - "==0" 
                - "==1"
                - ">=2"
        split_categories_binedges:
            njets: [-0.5,0.5,1.5,2.5]

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"

        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
        
        var_dependence: "pt_2"
        var_bins: [40,42.5,45,50,55,60,65,100]

    ttbar: 
        split_categories: 
            njets:  
                - "<=1"
                - ">=2"
        split_categories_binedges:
            njets: [-0.5,1.5,2.5]

        SR_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            nbtag: "nbtag >= 1"
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"

        AR_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            nbtag: "nbtag >= 1"
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
            had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            nbtag: "nbtag >= 1"
            no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5))"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            
        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            nbtag: "nbtag >= 1"
            no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5))"
            had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
        
        var_dependence: "pt_1"
        var_bins: [30,32,35,38,41,44,52,70,100]

process_fractions:
    processes: ["QCD", "Wjets", "ttbar_J"]

    split_categories:
        nbtag:
            - "==0"
            - "==1"
            - ">=2"
    split_categories_binedges:
        nbtag: [-0.5,0.5,1.5,2.5]

    AR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
        had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
        had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"

    SR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)"
        had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
        had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"

    var_dependence: "m_vis"
    var_bins: [20,30,40,50,60,70,80,90,100,110,120]