# This is an example config containing information for the FF corrections

channel: "mt" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            pt_1:
                var_dependence: "pt_1"
                correction_option: "smoothed"  # "binwise"
                split_categories:
                    njets:
                        - "==0"
                        - ">=1"
                split_categories_binedges:
                    njets: [-0.5, 0.5, 1.5]
                var_bins: [25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
            mass_2:
                var_dependence: "mass_2"
                correction_option: "smoothed"  # "binwise"
                split_categories:
                    njets:
                        - "==0"
                        - ">=1"
                split_categories_binedges:
                    njets: [-0.5, 0.5, 1.5]
                var_bins: [0.,0.2,0.4,0.6,0.8,1.,1.2,1.4,1.6,2.] 
            # iso_1:
            #     var_dependence: "iso_1"
            #     var_bins: [0.,0.01,0.05,0.1,0.15,0.2,0.25,0.31]
            #     SRlike_cuts:
            #         lep_iso: "iso_1 >= 0.0"
            #     ARlike_cuts:
            #         lep_iso: "iso_1 >= 0.0"  
                
        DR_SR:
            var_dependence: "m_vis"
            correction_option: "smoothed"  # "binwise"
            split_categories:
                njets:
                    - "==0"
                    - ">=1"
            split_categories_binedges:
                njets: [-0.5, 0.5, 1.5]
            var_bins: [0,50,75,100,120,140,160,180,250]
            SRlike_cuts:
                lep_iso: "(iso_1 >= 0.15) && (iso_1 < 0.3)"
            ARlike_cuts:
                lep_iso: "(iso_1 >= 0.15) && (iso_1 < 0.3)"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0" 
            non_closure:
                pt_1:
                    var_dependence: "pt_1"
                    correction_option: "smoothed"  # "binwise"
                    split_categories:
                        njets:
                            - "==0"
                            - ">=1"
                    split_categories_binedges:
                        njets: [-0.5, 0.5, 1.5]
                    var_bins: [25,30,35,40,45,50,55,60,65,70,80,100]
                mass_2:
                    var_dependence: "mass_2"
                    correction_option: "smoothed"  # "binwise"
                    split_categories:
                        njets:
                            - "==0"
                            - ">=1"
                    split_categories_binedges:
                        njets: [-0.5, 0.5, 1.5]
                    var_bins: [0.,0.2,0.4,0.6,0.8,1.,1.2,1.4,1.6,2.] 

    Wjets:
        non_closure:
            pt_1:
                var_dependence: "pt_1"
                correction_option: "smoothed"  # "binwise"
                split_categories:
                    njets:
                        - "==0"
                        - ">=1"
                split_categories_binedges:
                    njets: [-0.5, 0.5, 1.5]
                var_bins: [25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
            mass_2:
                var_dependence: "mass_2"
                correction_option: "smoothed"  # "binwise"
                split_categories:
                    njets:
                        - "==0"
                        - ">=1"
                split_categories_binedges:
                    njets: [-0.5, 0.5, 1.5]
                var_bins: [0.,0.2,0.4,0.6,0.8,1.,1.2,1.4,1.6,2.]
            # iso_1:
            #     var_dependence: "iso_1"
            #     var_bins: [0.,0.01,0.05,0.1,0.15,0.2,0.25,0.31]
            #     SRlike_cuts:
            #         lep_iso: "iso_1 >= 0.0"
            #     ARlike_cuts:
            #         lep_iso: "iso_1 >= 0.0"
                
        DR_SR:
            var_dependence: "m_vis"
            correction_option: "smoothed"  # "binwise"
            split_categories:
                njets:
                    - "==0"
                    - ">=1"
            split_categories_binedges:
                njets: [-0.5, 0.5, 1.5]
            var_bins: [0,40,70,100,140,180,250]
            SRlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            ARlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            AR_SR_cuts:
                nbtag: "(nbtag >= 1) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && fj_Xbb_pt > 200)"
            non_closure:
                pt_1:
                    var_dependence: "pt_1"
                    correction_option: "smoothed"  # "binwise"
                    split_categories:
                        njets:
                            - "==0"
                            - ">=1"
                    split_categories_binedges:
                        njets: [-0.5, 0.5, 1.5]
                    var_bins: [25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
                mass_2:
                    var_dependence: "mass_2"
                    correction_option: "smoothed"  # "binwise"
                    split_categories:
                        njets:
                            - "==0"
                            - ">=1"
                    split_categories_binedges:
                        njets: [-0.5, 0.5, 1.5]
                    var_bins: [0.,0.2,0.4,0.6,0.8,1.,1.2,1.4,1.6,2.] 


    ttbar:
        non_closure:
            pt_1:
                var_dependence: "pt_1"
                correction_option: "smoothed"  # "binwise"
                split_categories:
                    njets:
                        - "<=1"
                        - ">=2"
                split_categories_binedges:
                    njets: [-0.5, 0.5, 1.5]
                var_bins: [25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
            mass_2:
                var_dependence: "mass_2"
                correction_option: "smoothed"  # "binwise"
                split_categories:
                    njets:
                        - "<=1"
                        - ">=2"
                split_categories_binedges:
                    njets: [-0.5, 0.5, 1.5]
                var_bins: [0.,0.2,0.4,0.6,0.8,1.,1.2,1.4,1.6,2.]
