# This is an example config containing information for the FF corrections

channel: "tt" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            pt_2:
                var_dependence: "pt_2"
                var_bins: [40,60,80,100,120]
            mass_1:
                var_dependence: "mass_1"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]
            # m_vis:
            #     var_dependence: "m_vis"
            #     var_bins: [30,70,110,150]
                
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,20,40,60,80,100]
            SRlike_cuts:
                had_boostedtau_id_iso_2: "id_boostedtau_iso_Loose_2 < 0.5"
                # deltaR_ditaupair: "deltaR_ditaupair > 0.8"
            ARlike_cuts:
                had_boostedtau_id_iso_2: "id_boostedtau_iso_Loose_2 < 0.5"
                # deltaR_ditaupair: "deltaR_ditaupair > 0.8"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0"
            non_closure:
                pt_2:
                    var_dependence: "pt_2"
                    var_bins: [40,50,60,70,80,90,100,120]

    QCD_subleading:
        non_closure:
            pt_1:
                var_dependence: "pt_1"
                var_bins: [40,60,80,100,120]
            mass_2:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]
            # m_vis:
            #     var_dependence: "m_vis"
            #     var_bins: [30,70,110,150]

        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,20,40,60,80,100]
            SRlike_cuts:
                had_boostedtau_id_iso_1: "id_boostedtau_iso_Loose_1 < 0.5"
                # deltaR_ditaupair: "deltaR_ditaupair > 0.8"
            ARlike_cuts:
                had_boostedtau_id_iso_1: "id_boostedtau_iso_Loose_1 < 0.5"
                # deltaR_ditaupair: "deltaR_ditaupair > 0.8"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0"
            non_closure:
                pt_1:
                    var_dependence: "pt_1"
                    var_bins: [40,50,60,70,80,90,100,110,120]
        
    ttbar:
        non_closure:
            pt_2:
                var_dependence: "pt_2"
                var_bins: [40,60,80,100,120]
            mass_1:
                var_dependence: "mass_1"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]
    
    ttbar_subleading:
        non_closure:
            pt_1:
                var_dependence: "pt_1"
                var_bins: [40,60,80,100,120]
            mass_2:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]
