# This is an example config containing information for the FF corrections

workdir_name: "07_2024_v1_boosted"
era: "2018"
channel: "et" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [30,50,70,90,120,150,200]
            subleading_lep_mass:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.5,0.8,1.0,1.2,1.4,1.6,2.]
            # lep_mt:
            #     var_dependence: "mt_1"
            #     var_bins: [0,5,10,15,20,25,30,50]
        
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,40,50,60,70,80,90,100]
            # var_dependence: "deltaR_ditaupair"
            # var_bins: [0.1,0.4,0.5,0.6,0.7,0.8]
            SRlike_cuts:
                deltaR_ditaupair: "(deltaR_ditaupair > 0.8) || (deltaR_ditaupair < 0.1)"
            ARlike_cuts:
                deltaR_ditaupair: "(deltaR_ditaupair > 0.8) || (deltaR_ditaupair < 0.1)"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [30,40,60,80,100,120,140,170,210]

    Wjets:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [30,50,70,90,120,160]
            subleading_lep_mass:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.5,0.8,1.,1.2,1.4,1.6,2.]

        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,40,70]
            # var_dependence: "deltaR_ditaupair"
            # var_bins: [0.1,0.4,0.5,0.6,0.7,0.8]
            SRlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            ARlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            AR_SR_cuts:
                nbtag: "(nbtag >= 1) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && fj_Xbb_pt > 200)"
                # deltaR_ditaupair: "deltaR_ditaupair <= 0.8"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [30,50,70,90,120,160]

    ttbar:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [40,60,80,100,120,135,150,165,180,210]
            subleading_lep_mass:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.4,0.6,0.8,1.,1.2,1.4,1.6,2.]
            # m_vis:
            #     var_dependence: "m_vis"
            #     var_bins: [0,20,40,60,80,120]
