# This is an example config containing information for the FF corrections

workdir_name: "08_2024_v1"
era: "2018"
channel: "et" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [30,35,40,45,50,55,60,70,80,100]
            subleading_lep_mass:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.4,0.6,0.8,1.,1.2,1.4,1.6,2.]
            # lep_iso:
            #     var_dependence: "iso_1"
            #     var_bins: [0.,0.02,0.05,0.1,0.15,0.2,0.25,0.31]
            #     SRlike_cuts:
            #         lep_iso: "iso_1 >= 0.0"
            #     ARlike_cuts:
            #         lep_iso: "iso_1 >= 0.0"

        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,50,75,100,120,140,160,180,250]
            SRlike_cuts:
                lep_iso: "(iso_1 >= 0.15) && (iso_1 < 0.3)"
            ARlike_cuts:
                lep_iso: "(iso_1 >= 0.15) && (iso_1 < 0.3)"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [30,35,40,45,50,55,60,70,80,100]

    Wjets:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
            subleading_lep_mass:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.4,0.6,0.8,1.,1.2,1.4,1.6,2.]
            # lep_mt: 
            #     var_dependence: "mt_1"
            #     var_bins: [0,10,20,30,40,50,60,70,80,90,100,110,120,130]
            #     SRlike_cuts:
            #         lep_mt: "mt_1 >= 0.0"
            #     ARlike_cuts:
            #         lep_mt: "mt_1 >= 0.0"

        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,50,80,100,140,180,250]
            SRlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            ARlike_cuts:
                lep_mt: "mt_1 >= 0.0"
            AR_SR_cuts:
                nbtag: "(nbtag >= 1) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && fj_Xbb_pt > 200)"
            non_closure:
                leading_lep_pt:
                    var_dependence: "pt_1"
                    var_bins: [30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]

    ttbar:
        non_closure:
            leading_lep_pt:
                var_dependence: "pt_1"
                var_bins: [30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
            subleading_lep_mass:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.4,0.6,0.8,1.,1.2,1.4,1.6,2.]
