# This is an example config containing information for the FF calculation

channel: "tt" # options are et, mt, tt

use_embedding: False

target_processes: 
    QCD: 
        split_categories: 
            njets: 
                # - "==0" 
                - "<=1"
                - ">=2"
        split_categories_binedges:
            njets: [-0.5,1.5,2.5]

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"
        
        var_dependence: "pt_1"
        var_bins: [40,55,70,85,100]
        fit_option: ["poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]

    QCD_subleading: 
        split_categories: 
            njets: 
                # - "==0" 
                - "<=1"
                - ">=2"
        split_categories_binedges:
            njets: [-0.5,1.5,2.5]

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"
        
        var_dependence: "pt_2"
        var_bins: [40,50,70,100]
        fit_option: ["poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]

    ttbar: 
        split_categories: 
            njets:  
                - "<=2"
                - ">=3"
        split_categories_binedges:
            njets: [-0.5,2.5,3.5]

        SR_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            # nbtag: "nbtag >= 1"
            # m_vis: "m_vis <= 200." # needed due to embedding overestimation
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

        AR_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            # nbtag: "nbtag >= 1"
            # m_vis: "m_vis <= 200." # needed due to embedding overestimation
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            # nbtag: "nbtag >= 1"
            # m_vis: "m_vis <= 200." # needed due to embedding overestimation
            no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"
            
        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            # nbtag: "nbtag >= 1"
            # m_vis: "m_vis <= 200." # needed due to embedding overestimation
            no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
            had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"
        
        var_dependence: "pt_1"
        var_bins: [40,44,52,70,100]
        fit_option: ["poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]

    ttbar_subleading: 
        split_categories: 
            njets:  
                - "<=2"
                - ">=3"
        split_categories_binedges:
            njets: [-0.5,2.5,3.5]

        SR_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            # nbtag: "nbtag >= 1"
            # m_vis: "m_vis <= 200." # needed due to embedding overestimation
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

        AR_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            # nbtag: "nbtag >= 1"
            # m_vis: "m_vis <= 200." # needed due to embedding overestimation
            no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            # nbtag: "nbtag >= 1"
            # m_vis: "m_vis <= 200." # needed due to embedding overestimation
            no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"
            
        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) < 0" 
            # nbtag: "nbtag >= 1"
            # m_vis: "m_vis <= 200." # needed due to embedding overestimation
            no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
            had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
            had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
            bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"
        
        var_dependence: "pt_2"
        var_bins: [40,44,52,70,100]
        fit_option: ["poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]

process_fractions:
    processes: ["QCD", "Wjets", "ttbar_J"]

    split_categories:
        nbtag:
            - "<=1"
            - ">=2"
    split_categories_binedges:
        nbtag: [-0.5,1.5,2.5]

    AR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
        had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
        had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
        bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

    SR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
        had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
        had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
        bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

    var_dependence: "m_vis"
    var_bins: [0,50,70,90,110,130,150,170,190,210]

process_fractions_subleading:
    processes: ["QCD", "Wjets", "ttbar_J"]

    split_categories:
        nbtag:
            - "<=1"
            - ">=2"
    split_categories_binedges:
        nbtag: [-0.5,1.5,2.5]

    AR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
        had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
        had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
        bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

    SR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
        had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
        had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
        bb_selection: "(bpair_pt_1>=20 && bpair_pt_2>=20 && nbtag>=1 && bpair_btag_value_2>=0.049 && abs(bpair_eta_2)<=2.5) || (fj_Xbb_particleNet_XbbvsQCD>=0.6 && abs(fj_Xbb_eta)<=2.5 && fj_Xbb_pt>=200)"

    var_dependence: "m_vis"
    var_bins: [0,50,70,90,110,130,150,170,190,210]
