channel: mt
templates:
  split_schemes:
    3j: &3j_split
      split_categories: &3j_split_categories
        njets: ["==0", "==1", ">=2"]
      split_categories_binedges: &3j_split_categories_binedges
        njets: [-0.5, 0.5, 1.5, 22.5]
      correction_option:
        "==0": "smoothed"
        "==1": "smoothed"
        ">=2": "smoothed"
      bandwidth:
        "==0": 1.0
        "==1": 1.0
        ">=2": 1.0
    2j: &2j_split
      split_categories: &2j_split_categories
        njets: ["<=1", ">=2"]
      split_categories_binedges: &2j_split_categories_binedges
        njets: [-0.5, 1.5, 22.5]
      correction_option:
        "<=1": "smoothed"
        ">=2": "smoothed"
      bandwidth:
        "<=1": 1
        ">=2": 1
  var_dependence_n_bins:
    QCD:
      equipopulated_binning_options: &QCD_var_dependence_n_bins
        var_dependence_n_bins:
          "==0": 11
          "==1": 9
          ">=2": 7
    Wjets:
      equipopulated_binning_options: &Wjets_var_dependence_n_bins
        var_dependence_n_bins:
          "==0": 15
          "==1": 11
          ">=2": 9
    ttbar:
      equipopulated_binning_options: &ttbar_var_dependence_n_bins
        var_dependence_n_bins:
          "<=1": 11
          ">=2": 15
  variables:
    m_vis: &m_vis
      var_dependence: m_vis
      equipopulated_binning_options: &m_vis__eq_bin_opt
        variable_config:
          m_vis:
            min: 10.0
            max: 250.0
            rounding: 2
      correction_option: "smoothed"
    mass_2: &mass_2
      var_dependence: mass_2
      equipopulated_binning_options: &mass_2__eq_bin_opt
        variable_config:
          mass_2:
            min: 0.2
            max: 2.0
            rounding: 4
        add_left: [0.0]
      correction_option: "binwise#[0]+smoothed"
    tau_decaymode_2: &tau_decaymode_2
      var_dependence: tau_decaymode_2
      correction_option: "binwise"
      var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
    deltaR_ditaupair: &deltaR_ditaupair
      var_dependence: deltaR_ditaupair
      equipopulated_binning_options: &deltaR_ditaupair__eq_bin_opt
        variable_config:
          deltaR_ditaupair:
            min: 0.5
            max: 5.0
            rounding: 4
      correction_option: "smoothed"
    iso_1: &iso_1
      var_dependence: iso_1
      equipopulated_binning_options: &iso_1__eq_bin_opt
        variable_config:
          iso_1:
            min: 0.00005
            max: 0.15
            rounding: 6
        add_left: [0.0]
      correction_option: "binwise#[0]+smoothed"

target_processes:
  QCD:
    non_closure:
      m_vis:
        <<: [*m_vis, *3j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth:
          "==0": 20
          "==1": 35
          ">=2": 50
        var_bins:
          "==0": [10.0, 62.57, 66.96, 71.28, 75.86, 80.81, 86.89, 94.51, 105.32, 121.43, 147.86, 250.0]
          "==1": [10.0, 52.87, 64.52, 71.76, 79.13, 87.73, 99.12, 117.93, 148.5, 250.0]
          ">=2": [10.0, 50.01, 66.18, 78.78, 94.87, 113.93, 146.55, 250.0]
      mass_2:
        <<: [*mass_2, *3j_split]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth:
          "==0": 0.22
          "==1": 0.25
          ">=2": 0.25
        var_bins:
          "==0": [0.0, 0.2, 0.5107, 0.6216, 0.7388, 0.835, 0.9121, 0.9941, 1.0732, 1.1543, 1.25, 1.3623, 2.0]
          "==1": [0.0, 0.2, 0.5322, 0.665, 0.79, 0.896, 1.0088, 1.0957, 1.1982, 1.3271, 2.0]
          ">=2": [0.0, 0.2, 0.564, 0.7314, 0.8735, 0.9932, 1.1123, 1.2715, 2.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *3j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth:
          "==0": 0.45
          "==1": 0.9
          ">=2": 1.1
        var_bins:
          "==0": [0.5, 2.6814, 2.869, 2.9787, 3.0526, 3.1104, 3.1696, 3.2609, 3.3865, 3.5747, 3.9186, 5.0]
          "==1": [0.5, 1.653, 2.227, 2.5243, 2.7304, 2.9125, 3.0715, 3.2696, 3.6723, 5.0]
          ">=2": [0.5, 1.3291, 1.9185, 2.3753, 2.7661, 3.0644, 3.4088, 5.0]
      iso_1:
        <<: [*iso_1, *3j_split]
        equipopulated_binning_options:
          <<: *QCD_var_dependence_n_bins
          variable_config:
            iso_1:
              min: 0.05
              max: 0.15
              rounding: 4
        correction_option: "smoothed"
        bandwidth:
          "==0": 0.03
          "==1": 0.05
          ">=2": 0.05
        var_bins:
          "==0": [0.05, 0.0569, 0.0635, 0.0705, 0.0782, 0.0866, 0.0954, 0.1057, 0.1156, 0.1263, 0.1375, 0.15]
          "==1": [0.05, 0.0571, 0.0651, 0.074, 0.0835, 0.0967, 0.1086, 0.1223, 0.1349, 0.15]
          ">=2": [0.05, 0.0594, 0.0687, 0.0813, 0.0961, 0.1109, 0.1282, 0.15]
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *3j_split_categories, *3j_split_categories_binedges]

    DR_SR:
      <<: [*m_vis, *3j_split]
      equipopulated_binning_options:
        <<: [*m_vis__eq_bin_opt, *QCD_var_dependence_n_bins]
      bandwidth:
        "==0": 25
        "==1": 35
        ">=2": 55
      var_bins:
        "==0": [10.0, 62.66, 67.52, 72.19, 77.11, 82.6, 88.78, 96.52, 106.8, 122.18, 150.37, 250.0]
        "==1": [10.0, 53.71, 65.02, 73.84, 83.69, 94.61, 107.96, 125.85, 158.3, 250.0]
        ">=2": [10.0, 54.09, 70.73, 84.58, 99.76, 122.1, 160.66, 250.0]

      SRlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      ARlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      non_closure:
        mass_2:
          <<: [*mass_2, *3j_split]
          equipopulated_binning_options:
            <<: [*mass_2__eq_bin_opt, *QCD_var_dependence_n_bins]
          bandwidth:
            "==0": 0.22
            "==1": 0.25
            ">=2": 0.3
          var_bins:
            "==0": [0.0, 0.2, 0.5083, 0.6235, 0.73, 0.8232, 0.9072, 0.9854, 1.0664, 1.1514, 1.2432, 1.3594, 2.0]
            "==1": [0.0, 0.2, 0.5278, 0.6597, 0.7856, 0.8867, 0.9854, 1.084, 1.1895, 1.3301, 2.0]
            ">=2": [0.0, 0.2, 0.5796, 0.7485, 0.8813, 1.0, 1.1309, 1.2988, 2.0]
        deltaR_ditaupair:
          <<: [*deltaR_ditaupair, *3j_split]
          equipopulated_binning_options:
            <<: [*deltaR_ditaupair__eq_bin_opt, *QCD_var_dependence_n_bins]
          bandwidth:
            "==0": 0.4
            "==1": 0.9
            ">=2": 1.1
          var_bins:
            "==0": [0.5, 2.6207, 2.8253, 2.9447, 3.0246, 3.0866, 3.139, 3.2122, 3.3286, 3.5135, 3.8094, 5.0]
            "==1": [0.5, 1.5558, 2.1107, 2.4377, 2.702, 2.8996, 3.07, 3.2498, 3.5909, 5.0]
            ">=2": [0.5, 1.3348, 1.9419, 2.3913, 2.7351, 3.0277, 3.331, 5.0]
        tau_decaymode_2:
          <<: [*tau_decaymode_2, *3j_split_categories, *3j_split_categories_binedges]

  Wjets:
    non_closure:
      m_vis:
        <<: [*m_vis, *3j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *Wjets_var_dependence_n_bins]
        bandwidth:
          "==0": 20
          "==1": 25
          ">=2": 50
        var_bins:
          "==0": [10.0, 42.86, 56.57, 65.25, 71.44, 76.81, 82.65, 88.89, 94.81, 101.38, 108.76, 117.89, 129.67, 146.41, 173.6, 250.0]
          "==1": [10.0, 47.9, 61.79, 70.4, 78.55, 87.62, 97.03, 108.32, 123.11, 142.49, 172.66, 250.0]
          ">=2": [10.0, 52.86, 67.26, 77.69, 90.57, 104.12, 120.68, 142.58, 175.33, 250.0]
      mass_2:
        <<: [*mass_2, *3j_split]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *Wjets_var_dependence_n_bins]
        bandwidth:
          "==0": 0.17
          "==1": 0.21
          ">=2": 0.25
        var_bins:
          "==0": [0.0, 0.2, 0.4827, 0.5635, 0.6396, 0.707, 0.7681, 0.8281, 0.8857, 0.9453, 1.0078, 1.0713, 1.1377, 1.2109, 1.2949, 1.4092, 2.0]
          "==1": [0.0, 0.2, 0.5088, 0.6177, 0.7119, 0.7959, 0.8696, 0.9551, 1.0381, 1.1279, 1.2285, 1.3545, 2.0]
          ">=2": [0.0, 0.2, 0.5308, 0.6577, 0.7612, 0.8506, 0.957, 1.0625, 1.1758, 1.3076, 2.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *3j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *Wjets_var_dependence_n_bins]
        bandwidth:
          "==0": 0.3
          "==1": 0.425
          ">=2": 0.8
        var_bins:
          "==0": [0.5, 1.291, 1.6664, 1.9482, 2.1706, 2.3528, 2.5196, 2.6606, 2.783, 2.8902, 2.9821, 3.0643, 3.1321, 3.2287, 3.4481, 5.0]
          "==1": [0.5, 1.1946, 1.5966, 1.9154, 2.1746, 2.4058, 2.6139, 2.801, 2.9638, 3.1049, 3.3191, 5.0]
          ">=2": [0.5, 1.1567, 1.5816, 1.9338, 2.2206, 2.4933, 2.7366, 2.9631, 3.1951, 5.0]
      iso_1:
        <<: [*iso_1, *3j_split]
        equipopulated_binning_options:
          <<: [*iso_1__eq_bin_opt, *Wjets_var_dependence_n_bins]
          add_left: [0.0]
        bandwidth:
          "==0": 0.05
          "==1": 0.05
          ">=2": 0.07
        var_bins:
          "==0": [0.0, 0.00005, 0.004932, 0.007516, 0.010087, 0.012785, 0.015814, 0.019493, 0.023479, 0.028324, 0.034053, 0.040962, 0.049714, 0.060662, 0.075963, 0.100649, 0.15]
          "==1": [0.0, 0.00005, 0.005621, 0.009072, 0.012884, 0.017279, 0.022713, 0.029417, 0.037605, 0.049066, 0.064637, 0.090462, 0.15]
          ">=2": [0.0, 0.00005, 0.005602, 0.009668, 0.014723, 0.020748, 0.028099, 0.039254, 0.055474, 0.082078, 0.15]
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *3j_split_categories, *3j_split_categories_binedges]

    DR_SR:
      <<: [*m_vis, *3j_split]
      equipopulated_binning_options:
        <<: [*m_vis__eq_bin_opt, *Wjets_var_dependence_n_bins]
      bandwidth:
        "==0": 25
        "==1": 40
        ">=2": 50
      var_bins:
        "==0": [10.0, 59.17, 62.82, 65.39, 67.65, 69.8, 71.97, 74.32, 77.03, 80.47, 85.52, 91.72, 100.96, 116.47, 143.55, 250.0]
        "==1": [10.0, 49.72, 58.36, 63.36, 67.72, 72.15, 77.51, 85.59, 97.05, 115.78, 147.33, 250.0]
        ">=2": [10.0, 45.56, 55.23, 62.17, 68.46, 76.17, 89.17, 110.57, 145.99, 250.0]

      SRlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      ARlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))

      non_closure:
        mass_2:
          <<: [*mass_2, *3j_split]
          equipopulated_binning_options:
            <<: [*mass_2__eq_bin_opt, *Wjets_var_dependence_n_bins]
          bandwidth:
            "==0": 0.17
            "==1": 0.21
            ">=2": 0.25
          var_bins:
            "==0": [0.0, 0.2, 0.502, 0.5903, 0.665, 0.7246, 0.7759, 0.8286, 0.8857, 0.9468, 1.0088, 1.0713, 1.1348, 1.2021, 1.2812, 1.3877, 2.0]
            "==1": [0.0, 0.2, 0.5234, 0.6362, 0.7227, 0.7979, 0.8706, 0.9541, 1.0391, 1.124, 1.2197, 1.3428, 2.0]
            ">=2": [0.0, 0.2, 0.5518, 0.6743, 0.7671, 0.8555, 0.957, 1.0576, 1.1689, 1.3057, 2.0]
        deltaR_ditaupair:
          <<: [*deltaR_ditaupair, *3j_split]
          equipopulated_binning_options:
            <<: [*deltaR_ditaupair__eq_bin_opt, *Wjets_var_dependence_n_bins]
          bandwidth:
            "==0": 0.25
            "==1": 0.5
            ">=2": 0.85
          var_bins:
            "==0": [0.5, 2.0842, 2.478, 2.6807, 2.8084, 2.897, 2.9626, 3.0133, 3.0546, 3.0884, 3.1171, 3.1425, 3.1824, 3.2541, 3.4196, 5.0]
            "==1": [0.5, 1.223, 1.606, 1.9029, 2.1506, 2.3674, 2.5644, 2.7506, 2.9215, 3.0685, 3.2314, 5.0]
            ">=2": [0.5, 0.9449, 1.2582, 1.5533, 1.8676, 2.1892, 2.5238, 2.8292, 3.1081, 5.0]
        iso_1:
          <<: [*iso_1, *3j_split]
          equipopulated_binning_options:
            <<: [*iso_1__eq_bin_opt, *Wjets_var_dependence_n_bins]
          bandwidth:
            "==0": 0.03
            "==1": 0.045
            ">=2": 0.06
          var_bins:
            "==0": [0.0, 0.00005, 0.006526, 0.009751, 0.013092, 0.016668, 0.020633, 0.025075, 0.030223, 0.036122, 0.043029, 0.051348, 0.061142, 0.073611, 0.090068, 0.113631, 0.15]
            "==1": [0.0, 0.00005, 0.006854, 0.011091, 0.015666, 0.02097, 0.027364, 0.035134, 0.044877, 0.057478, 0.074701, 0.101279, 0.15]
            ">=2": [0.0, 0.00005, 0.006986, 0.012023, 0.017947, 0.025218, 0.034305, 0.046886, 0.064644, 0.092354, 0.15]
        tau_decaymode_2:
          <<: [*tau_decaymode_2, *3j_split_categories, *3j_split_categories_binedges]

  ttbar:
    non_closure:
      m_vis:
        <<: [*m_vis, *2j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "<=1": 28
          ">=2": 36
        var_bins:
          "<=1": [10.0, 55.86, 65.63, 72.36, 79.46, 86.85, 92.84, 101.48, 112.62, 129.11, 156.72, 250.0]
          ">=2": [10.0, 38.19, 49.23, 58.54, 66.52, 73.73, 80.35, 87.79, 94.93, 103.08, 111.97, 122.64, 136.18, 155.85, 185.32, 250.0]
      mass_2:
        <<: [*mass_2, *2j_split]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "<=1": 0.2
          ">=2": 0.17
        var_bins:
          "<=1": [0.0, 0.2, 0.5083, 0.6133, 0.7085, 0.7949, 0.874, 0.9585, 1.042, 1.1299, 1.2266, 1.3506, 2.0]
          ">=2": [0.0, 0.2, 0.4604, 0.5337, 0.6133, 0.6826, 0.7583, 0.8193, 0.8711, 0.9282, 0.9922, 1.0518, 1.125, 1.2041, 1.2861, 1.3975, 2.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *2j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "<=1": 0.35
          ">=2": 0.9
        var_bins:
          "<=1": [0.5, 1.6378, 2.1293, 2.4506, 2.657, 2.8131, 2.9466, 3.043, 3.1206, 3.2206, 3.4656, 5.0]
          ">=2": [0.5, 0.8718, 1.1652, 1.4329, 1.6809, 1.8815, 2.0858, 2.2699, 2.4319, 2.6061, 2.7768, 2.9312, 3.0649, 3.206, 3.4749, 5.0]
      iso_1:
        <<: [*iso_1, *2j_split]
        equipopulated_binning_options:
          <<: [*iso_1__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "<=1": 0.05
          ">=2": 0.05
        var_bins:
          "<=1": [0.0, 0.00005, 0.006078, 0.009497, 0.013293, 0.017497, 0.022521, 0.029847, 0.038228, 0.04938, 0.065122, 0.09265, 0.15]
          ">=2": [0.0, 0.00005, 0.004539, 0.006799, 0.008935, 0.011234, 0.013793, 0.016743, 0.020174, 0.024425, 0.030233, 0.037938, 0.045416, 0.056526, 0.073012, 0.09402, 0.15]
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *2j_split_categories, *2j_split_categories_binedges]
