channel: mt
target_processes:
  QCD:
    non_closure:
      pt_1:
        var_dependence: pt_1
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [25, 30, 35, 40, 50, 60, 70, 80,      140]
          "==1": [25, 30, 35, 40, 50, 60,     80,      140]
          ">=2": [25, 30, 35, 40,     60,     80,      140]
      tau_decaymode_2:
        var_dependence: tau_decaymode_2
        write_corrections: "binwise"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
      iso_1:
        var_dependence: iso_1
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [0.05, 0.0625, 0.075, 0.0875, 0.10, 0.1125, 0.125, 0.1375, 0.15]
          "==1": [0.05,         0.075,         0.10,         0.125,         0.15]
          ">=2": [0.05,                        0.10,                        0.15]
      mass_2:
        var_dependence: mass_2
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
          "==1": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
          ">=2": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]

    DR_SR:
      var_dependence: m_vis
      write_corrections: "smoothed"
      bandwidth: 40
      split_categories:
        njets:
          - "==0"
          - "==1"
          - ">=2"
      split_categories_binedges:
        njets: [-0.5, 0.5, 1.5, 12.5]
      var_bins: 
        "==0": [0,     60, 70, 80, 90, 100, 110, 120, 130, 150, 170, 190, 210, 300]
        "==1": [0, 50,     70,     90,      110,      130, 150,           200, 300]
        ">=2": [0, 50,     70,     90,      110,      130, 150,           200, 300]

      SRlike_cuts: # NOCHMALS ORTHOGONAL ZU fake_factors_mt.yaml (komplett neue ff)
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      ARlike_cuts: # NOCHMALS ORTHOGONAL ZU fake_factors_mt.yaml
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"  
      non_closure:
        pt_1:
          var_dependence: pt_1
          write_corrections: "smoothed"
          bandwidth: 15
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: 
            "==0": [25, 30, 35, 40, 50, 60, 70, 80, 100, 140]
            "==1": [25, 30, 35, 40, 50, 60,     80,      140]
            ">=2": [25, 30, 35, 40, 50, 60,     80,      140]
        tau_decaymode_2:
          var_dependence: tau_decaymode_2
          write_corrections: "binwise"
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
        mass_2:
          var_dependence: mass_2
          write_corrections: "smoothed"
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: 
            "==0": [0.0, 0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
            "==1": [0.0, 0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
            ">=2": [0.0, 0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]

  Wjets:
    non_closure:
      pt_1:
        var_dependence: pt_1
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins:
          "==0": [25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 125, 150]
          "==1": [25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 125, 150]
          ">=2": [25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 125, 150]
      tau_decaymode_2:
        var_dependence: tau_decaymode_2
        write_corrections: "binwise"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
      iso_1:
        var_dependence: iso_1
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [0.0, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.15]
          "==1": [0.0, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.15]
          ">=2": [0.0,       0.02,       0.06,       0.10,       0.15]
      mass_2:
        var_dependence: mass_2
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
          "==1": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
          ">=2": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]

    DR_SR:
      m_vis:  
      var_dependence: m_vis
      write_corrections: "smoothed"
      split_categories:
        njets:
          - "==0"
          - "==1"
          - ">=2"
      split_categories_binedges:
        njets: [-0.5, 0.5, 1.5, 12.5]
      var_bins: 
        "==0": [0, 35, 50, 60, 70, 80, 90, 100, 110, 120, 130, 150, 200, 300]
        "==1": [0, 35, 50, 60, 70, 80, 90, 100, 110, 120, 130, 150, 200, 300]
        ">=2": [0,     50,     70,     90,      110,      130, 150, 200, 300]

      SRlike_cuts:
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      ARlike_cuts:
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))

      non_closure:
        pt_1:
          var_dependence: pt_1
          write_corrections: "smoothed"
          bandwidth: 15
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins:
            "==0": [25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 125, 150]
            "==1": [25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 125, 150]
            ">=2": [25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 125, 150]
        tau_decaymode_2:
          var_dependence: tau_decaymode_2
          write_corrections: "binwise"
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
        iso_1:
          var_dependence: iso_1
          write_corrections: "smoothed"
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: 
            "==0": [0.0, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.15]
            "==1": [0.0, 0.01, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.15]
            ">=2": [0.0,       0.02,       0.06,       0.10,       0.15]
        mass_2:
          var_dependence: mass_2
          write_corrections: "smoothed"
          bandwidth: 0.2
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: 
            "==0": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
            "==1": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
            ">=2": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]

  ttbar:
    non_closure:
      pt_1:
        var_dependence: pt_1
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "<=1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 1.5, 12.5]
        var_bins: 
          "<=1": [25, 30, 35, 40, 50, 60, 80, 100, 140]
          ">=2": [25, 30, 35, 40, 50, 60, 80, 100, 140]
      tau_decaymode_2:
        var_dependence: tau_decaymode_2
        write_corrections: "binwise"
        split_categories:
          njets:
            - "<=1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 1.5, 12.5]
        var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
      iso_1:
        var_dependence: iso_1
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "<=1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 1.5, 12.5]
        var_bins:
          "<=1": [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15]
          ">=2": [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15]
      mass_2:
        var_dependence: mass_2
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "<=1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 1.5, 12.5]
        var_bins:
          "<=1": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
          ">=2": [0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.7]
