channel: mt
target_processes:
  QCD:
    non_closure:
      pt_1:
        var_dependence: pt_1
        write_corrections: "smoothed"  # "binwise"
        split_categories:
          njets:
            - "==0"
            - ">=1"
        split_categories_binedges:
          njets: [-0.5, 0.5, 12.5]
        var_bins:
          "==0": [25, 30, 35, 40, 50, 60]
          ">=1": [25, 30,     40,     60]

      tau_decaymode_2:
        var_dependence: tau_decaymode_2
        write_corrections: "binwise"
        split_categories:
          njets:
            - "==0"
            - ">=1"
        split_categories_binedges:
          njets: [-0.5, 0.5, 12.5]
        var_bins:
          "==0": [-0.5, 0.5, 9.5, 10.5, 11.5]
          ">=1": [-0.5, 0.5, 9.5, 10.5, 11.5]

    DR_SR:
      var_dependence: m_vis
      var_bins: [0, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 170]
      write_corrections: "smoothed"


      SRlike_cuts: # NOCHMALS ORTHOGONAL ZU fake_factors_mt.yaml (komplett neue ff)
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"

      ARlike_cuts: # NOCHMALS ORTHOGONAL ZU fake_factors_mt.yaml
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"

      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"

      non_closure:
        pt_1:
          var_dependence: pt_1
          var_bins: [25, 30, 35, 40, 45, 50, 60]
          write_corrections: "smoothed"

  Wjets:
    non_closure:
      pt_1:
        var_dependence: pt_1
        write_corrections: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins:
          "==0": [25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 110]
          "==1": [25, 30, 35, 40, 45, 50,     60,     80,     110]
          ">=2": [25, 30, 35, 40,     50,     60,     80,     110]

      tau_decaymode_2:
        var_dependence: tau_decaymode_2
        write_corrections: "binwise"
        split_categories:
          njets:
            - "==0"
            - ">=1"
        split_categories_binedges:
          njets: [-0.5, 0.5, 12.5]
        var_bins:
          "==0": [-0.5, 0.5, 9.5, 10.5, 11.5]
          ">=1": [-0.5, 0.5, 9.5, 10.5, 11.5]

    DR_SR:
      var_dependence: m_vis
      var_bins: [0, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 170]
      write_corrections: "smoothed"

      SRlike_cuts:
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      ARlike_cuts:
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))

      non_closure:
        pt_1:
          var_dependence: pt_1
          var_bins: [25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 100, 110, 120]
          write_corrections: "smoothed"

  ttbar:
    non_closure:
      pt_1:
        var_dependence: pt_1
        write_corrections: "smoothed"  # "binwise"
        split_categories:
          njets:
            - ">=0"
        split_categories_binedges:
          njets: [-0.5, 12.5]
        var_bins: [25, 30, 35, 40, 50, 60]

      tau_decaymode_2:
        var_dependence: tau_decaymode_2
        write_corrections: "binwise"
        split_categories:
          njets:
            - ">=0"
        split_categories_binedges:
          njets: [-0.5, 12.5]
        var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
