templates:
  split_schemes:
    3j: &3j_split
      split_categories:
        njets: ["==0", "==1", ">=2"]
      split_categories_binedges:
        njets: [-0.5, 0.5, 1.5, 22.5]
      correction_option:
        "==0": "smoothed"
        "==1": "smoothed"
        ">=2": "smoothed"
      bandwidth:
        "==0": 1.0
        "==1": 1.0
        ">=2": 1.0
    2j: &2j_split
      split_categories:
        njets: ["<=1", ">=2"]
      split_categories_binedges:
        njets: [-0.5, 1.5, 22.5]
      correction_option:
        "<=1": "smoothed"
        ">=2": "smoothed"
      bandwidth:
        "<=1": 1
        ">=2": 1
  var_dependence_n_bins:
    QCD:
      equipopulated_binning_options: &QCD_var_dependence_n_bins
        var_dependence_n_bins:
          "==0": 11
          "==1": 9
          ">=2": 7
    Wjets:
      equipopulated_binning_options: &Wjets_var_dependence_n_bins
        var_dependence_n_bins:
          "==0": 15
          "==1": 11
          ">=2": 9
    ttbar:
      equipopulated_binning_options: &ttbar_var_dependence_n_bins
        var_dependence_n_bins:
          "<=1": 11
          ">=2": 15
  variables:
    deltaR_ditaupair: &deltaR_ditaupair
      var_dependence: deltaR_ditaupair
      equipopulated_binning_options: &deltaR_ditaupair__eq_bin_opt
        variable_config:
          deltaR_ditaupair:
            min: 0.5
            max: 5.0
            rounding: 4
      correction_option: "smoothed"
    m_vis: &m_vis
      var_dependence: m_vis
      equipopulated_binning_options: &m_vis__eq_bin_opt
        variable_config:
          m_vis:
            min: 10.0
            max: 250.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    mass_2: &mass_2
      var_dependence: mass_2
      equipopulated_binning_options: &mass_2__eq_bin_opt
        variable_config:
          mass_2:
            min: 0.2
            max: 2.0
            rounding: 4
        add_left: [0.0]
      correction_option: "binwise#[0]+smoothed"
      bandwidth: 0.3
    tau_decaymode_2: &tau_decaymode_2
      var_dependence: tau_decaymode_2
      correction_option: "binwise"
      bandwidth: 1.0
      var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
    iso_1: &iso_1
      var_dependence: iso_1
      equipopulated_binning_options: &iso_1__eq_bin_opt
        variable_config:
          iso_1:
            min: 0.00005
            max: 0.15
            rounding: 6
        add_left: [0.0]
      correction_option: "binwise#[0]+smoothed"
      bandwidth: 0.02


channel: mt
target_processes:
  QCD:
    chain_DR_SR_to_non_closure: true
    non_closure:
      m_vis:
        <<: [*m_vis, *3j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: [20, 20.0, 50.0]
        var_bins:
          "==0": [10.0, 62.57, 66.96, 71.28, 75.86, 80.81, 86.89, 94.51, 105.32, 121.43, 147.86, 250.0]
          "==1": [10.0, 52.87, 64.52, 71.76, 79.13, 87.73, 99.12, 117.93, 148.5, 250.0]
          ">=2": [10.0, 50.01, 66.18, 78.78, 94.87, 113.93, 146.55, 250.0]
      mass_2:
        <<: [*mass_2, *3j_split]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: [0.20, 0.20, 0.3]
        var_bins:
          "==0": [0.0, 0.2, 0.5107, 0.6216, 0.7388, 0.835, 0.9121, 0.9941, 1.0732, 1.1543, 1.25, 1.3623, 2.0]
          "==1": [0.0, 0.2, 0.5322, 0.665, 0.79, 0.896, 1.0088, 1.0957, 1.1982, 1.3271, 2.0]
          ">=2": [0.0, 0.2, 0.564, 0.7314, 0.8735, 0.9932, 1.1123, 1.2715, 2.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *3j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: [0.6, 0.8, 1.1]
        var_bins:
          "==0": [0.5, 2.6814, 2.869, 2.9787, 3.0526, 3.1104, 3.1696, 3.2609, 3.3865, 3.5747, 3.9186, 5.0]
          "==1": [0.5, 1.653, 2.227, 2.5243, 2.7304, 2.9125, 3.0715, 3.2696, 3.6723, 5.0]
          ">=2": [0.5, 1.3291, 1.9185, 2.3753, 2.7661, 3.0644, 3.4088, 5.0]
      iso_1:
        <<: [*iso_1, *3j_split]
        equipopulated_binning_options:
          <<: *QCD_var_dependence_n_bins
          variable_config:
            iso_1:
              min: 0.05
              max: 0.15
              rounding: 6
        bandwidth: [0.03, 0.04, 0.04]
        correction_option: "smoothed"
        var_bins:
          "==0": [0.05, 0.056882, 0.063543, 0.070468, 0.078181, 0.086647, 0.095377, 0.105744, 0.115638, 0.126327, 0.137486, 0.15]
          "==1": [0.05, 0.057096, 0.065105, 0.073987, 0.083517, 0.096737, 0.108642, 0.122276, 0.13489, 0.15]
          ">=2": [0.05, 0.059351, 0.068657, 0.081325, 0.096132, 0.110882, 0.128247, 0.15]
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *3j_split]
      
    DR_SR:
      <<: [*m_vis, *3j_split]
      equipopulated_binning_options:
        <<: [*m_vis__eq_bin_opt, *QCD_var_dependence_n_bins]
      bandwidth: [15, 25, 55]
      var_bins:
        "==0": [10.0, 62.66, 67.52, 72.19, 77.11, 82.6, 88.78, 96.52, 106.8, 122.18, 150.37, 250.0]
        "==1": [10.0, 53.71, 65.02, 73.84, 83.69, 94.61, 107.96, 125.85, 158.3, 250.0]
        ">=2": [10.0, 54.09, 70.73, 84.58, 99.76, 122.1, 160.66, 250.0]

      SRlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      ARlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      non_closure:
        tau_decaymode_2:
          <<: [*tau_decaymode_2, *3j_split]

  Wjets:
    chain_DR_SR_to_non_closure: true
    non_closure:
      m_vis:
        <<: [*m_vis, *3j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *Wjets_var_dependence_n_bins]
        bandwidth: [15, 20, 25]
        var_bins:
          "==0": [10.0, 42.86, 56.57, 65.25, 71.44, 76.81, 82.65, 88.89, 94.81, 101.38, 108.76, 117.89, 129.67, 146.41, 173.6, 250.0]
          "==1": [10.0, 47.9, 61.79, 70.4, 78.55, 87.62, 97.03, 108.32, 123.11, 142.49, 172.66, 250.0]
          ">=2": [10.0, 52.86, 67.26, 77.69, 90.57, 104.12, 120.68, 142.58, 175.33, 250.0]
      mass_2:
        <<: [*mass_2, *3j_split]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *Wjets_var_dependence_n_bins]
        bandwidth: [0.2, 0.2, 0.2]
        var_bins:
          "==0": [0.0, 0.2, 0.4827, 0.5635, 0.6396, 0.707, 0.7681, 0.8281, 0.8857, 0.9453, 1.0078, 1.0713, 1.1377, 1.2109, 1.2949, 1.4092, 2.0]
          "==1": [0.0, 0.2, 0.5088, 0.6177, 0.7119, 0.7959, 0.8696, 0.9551, 1.0381, 1.1279, 1.2285, 1.3545, 2.0]
          ">=2": [0.0, 0.2, 0.5308, 0.6577, 0.7612, 0.8506, 0.957, 1.0625, 1.1758, 1.3076, 2.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *3j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *Wjets_var_dependence_n_bins]
        bandwidth: [0.25, 0.3, 0.5]
        var_bins:
          "==0": [0.5, 1.291, 1.6664, 1.9482, 2.1706, 2.3528, 2.5196, 2.6606, 2.783, 2.8902, 2.9821, 3.0643, 3.1321, 3.2287, 3.4481, 5.0]
          "==1": [0.5, 1.1946, 1.5966, 1.9154, 2.1746, 2.4058, 2.6139, 2.801, 2.9638, 3.1049, 3.3191, 5.0]
          ">=2": [0.5, 1.1567, 1.5816, 1.9338, 2.2206, 2.4933, 2.7366, 2.9631, 3.1951, 5.0]
      iso_1:
        <<: [*iso_1, *3j_split]
        equipopulated_binning_options:
          <<: [*iso_1__eq_bin_opt, *Wjets_var_dependence_n_bins]
        bandwidth: [0.02, 0.03, 0.03]
        var_bins:
          "==0": [0.0, 0.00005, 0.004932, 0.007516, 0.010087, 0.012785, 0.015814, 0.019493, 0.023479, 0.028324, 0.034053, 0.040962, 0.049714, 0.060662, 0.075963, 0.100649, 0.15]
          "==1": [0.0, 0.00005, 0.005621, 0.009072, 0.012884, 0.017279, 0.022713, 0.029417, 0.037605, 0.049066, 0.064637, 0.090462, 0.15]
          ">=2": [0.0, 0.00005, 0.005602, 0.009668, 0.014723, 0.020748, 0.028099, 0.039254, 0.055474, 0.082078, 0.15]
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *3j_split]
      
    DR_SR:
      <<: [*m_vis, *3j_split]
      equipopulated_binning_options:
        <<: [*m_vis__eq_bin_opt, *Wjets_var_dependence_n_bins]
      bandwidth: [10.0, 12.5, 25.0]
      var_bins:
        "==0": [10.0, 59.17, 62.82, 65.39, 67.65, 69.8, 71.97, 74.32, 77.03, 80.47, 85.52, 91.72, 100.96, 116.47, 143.55, 250.0]
        "==1": [10.0, 49.72, 58.36, 63.36, 67.72, 72.15, 77.51, 85.59, 97.05, 115.78, 147.33, 250.0]
        ">=2": [10.0, 45.56, 55.23, 62.17, 68.46, 76.17, 89.17, 110.57, 145.99, 250.0]

      SRlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      ARlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))

      non_closure:
        tau_decaymode_2:
          <<: [*tau_decaymode_2, *3j_split]


  ttbar:
    non_closure:
      m_vis:
        <<: [*m_vis, *2j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth: [10, 20]
        var_bins:
          "<=1": [10.0, 55.86, 65.63, 72.36, 79.46, 86.85, 92.84, 101.48, 112.62, 129.11, 156.72, 250.0]
          ">=2": [10.0, 38.19, 49.23, 58.54, 66.52, 73.73, 80.35, 87.79, 94.93, 103.08, 111.97, 122.64, 136.18, 155.85, 185.32, 250.0]
      mass_2:
        <<: [*mass_2, *2j_split]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth: [0.2, 0.15]
        var_bins:
          "<=1": [0.0, 0.2, 0.5083, 0.6133, 0.7085, 0.7949, 0.874, 0.9585, 1.042, 1.1299, 1.2266, 1.3506, 2.0]
          ">=2": [0.0, 0.2, 0.4604, 0.5337, 0.6133, 0.6826, 0.7583, 0.8193, 0.8711, 0.9282, 0.9922, 1.0518, 1.125, 1.2041, 1.2861, 1.3975, 2.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *2j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth: [0.2, 0.9]
        var_bins:
          "<=1": [0.5, 1.6378, 2.1293, 2.4506, 2.657, 2.8131, 2.9466, 3.043, 3.1206, 3.2206, 3.4656, 5.0]
          ">=2": [0.5, 0.8718, 1.1652, 1.4329, 1.6809, 1.8815, 2.0858, 2.2699, 2.4319, 2.6061, 2.7768, 2.9312, 3.0649, 3.206, 3.4749, 5.0]
      iso_1:
        <<: [*iso_1, *2j_split]
        equipopulated_binning_options:
          <<: [*iso_1__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth: [0.03, 0.03]
        var_bins:
          "<=1": [0.0, 0.00005, 0.006078, 0.009497, 0.013293, 0.017497, 0.022521, 0.029847, 0.038228, 0.04938, 0.065122, 0.09265, 0.15]
          ">=2": [0.0, 0.00005, 0.004539, 0.006799, 0.008935, 0.011234, 0.013793, 0.016743, 0.020174, 0.024425, 0.030233, 0.037938, 0.045416, 0.056526, 0.073012, 0.09402, 0.15]
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *2j_split]
      
