channel: mt
target_processes:
  QCD:
    non_closure:
      m_vis:
        var_dependence: m_vis
        correction_option: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        bandwidth:
          "==0": 45
          "==1": 45
          ">=2": 60
        var_bins:
          "==0": [0.00, 62.58, 67.06, 71.40, 76.02, 80.97, 87.21, 95.13, 105.98, 122.57, 150.41, 300.00]
          "==1": [0.00, 50.06, 61.35, 68.06, 74.18, 80.07, 87.39, 96.76, 109.17, 131.82, 161.42, 300.00]
          ">=2": [0.00, 42.07, 56.44, 65.57, 73.24, 81.95, 92.96, 103.53, 117.75, 137.30, 169.93, 300.00]
      mass_2:
        var_dependence: mass_2
        # correction_option: "smoothed"
        bandwidth: 0.3
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [0.0000, 0.2000, 0.5107, 0.6216, 0.7397, 0.8350, 0.9131, 0.9941, 1.0742, 1.1553, 1.2520, 1.3643, 3.0000]
          "==1": [0.0000, 0.2000, 0.5138, 0.6166, 0.7203, 0.8200, 0.9048, 0.9940, 1.0742, 1.1533, 1.2451, 1.3649, 3.0000]
          ">=2": [0.0000, 0.2000, 0.5010, 0.6084, 0.7148, 0.8169, 0.8945, 0.9780, 1.0566, 1.1328, 1.2285, 1.3486, 3.0000]
      deltaR_ditaupair:
        var_dependence: deltaR_ditaupair
        correction_option: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [1.5000, 2.6814, 2.8685, 2.9789, 3.0521, 3.1104, 3.1690, 3.2610, 3.3868, 3.5757, 3.9129, 5.0000]
          "==1": [0.5000, 1.5267, 2.0637, 2.3834, 2.5947, 2.7513, 2.8936, 3.0305, 3.1515, 3.3850, 3.7487, 5.0000]
          ">=2": [0.5000, 1.0810, 1.5235, 1.8794, 2.1892, 2.4695, 2.6882, 2.9270, 3.0915, 3.2845, 3.6045, 5.0000]
      iso_1:
        var_dependence: iso_1
        correction_option: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [0.0500, 0.0569, 0.0636, 0.0705, 0.0783, 0.0868, 0.0958, 0.1060, 0.1159, 0.1265, 0.1375, 0.1500]
          "==1": [0.0500, 0.0555, 0.0626, 0.0692, 0.0767, 0.0845, 0.0954, 0.1053, 0.1161, 0.1267, 0.1377, 0.1500]
          ">=2": [0.0500, 0.0562, 0.0618, 0.0679, 0.0761, 0.0842, 0.0931, 0.1027, 0.1127, 0.1240, 0.1376, 0.1500]
      tau_decaymode_2:
        var_dependence: tau_decaymode_2
        correction_option: "binwise"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]

    DR_SR:
      var_dependence: m_vis
      correction_option: "smoothed"
      bandwidth:
          "==0": 45
          "==1": 45
          ">=2": 60
      split_categories:
        njets:
          - "==0"
          - "==1"
          - ">=2"
      split_categories_binedges:
        njets: [-0.5, 0.5, 1.5, 12.5]
      var_bins: 
        "==0": [0.00, 62.58, 67.06, 71.40, 76.02, 80.97, 87.21, 95.13, 105.98, 122.57, 150.41, 300.00]
        "==1": [0.00, 50.06, 61.35, 68.06, 74.18, 80.07, 87.39, 96.76, 109.17, 131.82, 161.42, 300.00]
        ">=2": [0.00, 42.07, 56.44, 65.57, 73.24, 81.95, 92.96, 103.53, 117.75, 137.30, 169.93, 300.00]


      SRlike_cuts: # NOCHMALS ORTHOGONAL ZU fake_factors_mt.yaml (komplett neue ff)
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      ARlike_cuts: # NOCHMALS ORTHOGONAL ZU fake_factors_mt.yaml
        lep_mt: (mt_1 < 50)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"  
      non_closure:
        mass_2:
          var_dependence: mass_2
          correction_option: "smoothed"
          bandwidth: 0.3
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: 
            "==0": [0.0000, 0.2000, 0.5107, 0.6216, 0.7397, 0.8350, 0.9131, 0.9941, 1.0742, 1.1553, 1.2520, 1.3643, 3.0000]
            "==1": [0.0000, 0.2000, 0.5138, 0.6166, 0.7203, 0.8200, 0.9048, 0.9940, 1.0742, 1.1533, 1.2451, 1.3649, 3.0000]
            ">=2": [0.0000, 0.2000, 0.5010, 0.6084, 0.7148, 0.8169, 0.8945, 0.9780, 1.0566, 1.1328, 1.2285, 1.3486, 3.0000]
        deltaR_ditaupair:
          var_dependence: deltaR_ditaupair
          correction_option: "smoothed"
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          bandwidth:
            "==0": 0.7
            "==1": 0.9
            ">=2": 0.9
          var_bins: 
            "==0": [1.5000, 2.6814, 2.8685, 2.9789, 3.0521, 3.1104, 3.1690, 3.2610, 3.3868, 3.5757, 3.9129, 5.0000]
            "==1": [0.5000, 1.5267, 2.0637, 2.3834, 2.5947, 2.7513, 2.8936, 3.0305, 3.1515, 3.3850, 3.7487, 5.0000]
            ">=2": [0.5000, 1.0810, 1.5235, 1.8794, 2.1892, 2.4695, 2.6882, 2.9270, 3.0915, 3.2845, 3.6045, 5.0000]
        tau_decaymode_2:
          var_dependence: tau_decaymode_2
          correction_option: "binwise"
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]

  Wjets:
    non_closure:
      m_vis:
        var_dependence: m_vis
        correction_option: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        bandwidth:
          "==0": 45
          "==1": 60
          ">=2": 60
        var_bins:
          "==0": [0.00, 48.15, 63.12, 71.85, 79.39, 87.73, 95.99, 105.43, 117.69, 135.34, 165.45, 300.00]
          "==1": [0.00, 48.00, 61.83, 70.53, 78.74, 88.07, 97.60, 109.48, 124.89, 145.77, 180.78, 300.00]
          ">=2": [0.00, 49.56, 63.32, 72.24, 81.50, 92.65, 104.18, 117.74, 135.60, 158.54, 194.66, 300.00]
      mass_2:
        var_dependence: mass_2
        correction_option: "smoothed"
        bandwidth: 0.3
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [0.0000, 0.2000, 0.5127, 0.6201, 0.7119, 0.7964, 0.8750, 0.9575, 1.0439, 1.1318, 1.2328, 1.3652, 3.0000]
          "==1": [0.0000, 0.2000, 0.5098, 0.6187, 0.7124, 0.7954, 0.8696, 0.9556, 1.0391, 1.1279, 1.2295, 1.3584, 3.0000]
          ">=2": [0.0000, 0.2000, 0.5059, 0.6133, 0.7070, 0.7896, 0.8579, 0.9468, 1.0342, 1.1221, 1.2188, 1.3457, 3.0000]
      deltaR_ditaupair:
        var_dependence: deltaR_ditaupair
        correction_option: "smoothed"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [0.5000, 1.4423, 1.8695, 2.1822, 2.4266, 2.6347, 2.8038, 2.9434, 3.0582, 3.1506, 3.3521, 5.0000]
          "==1": [0.5000, 1.1901, 1.5941, 1.9140, 2.1734, 2.4031, 2.6121, 2.7999, 2.9632, 3.1052, 3.3221, 5.0000]
          ">=2": [0.5000, 1.0649, 1.4358, 1.7458, 2.0092, 2.2510, 2.4699, 2.6779, 2.8644, 3.0490, 3.2758, 5.0000]
      iso_1:
        var_dependence: iso_1
        correction_option: "smoothed"
        bandwidth: 0.04
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: 
          "==0": [0.0000, 0.0001, 0.0059, 0.0093, 0.0130, 0.0175, 0.0227, 0.0291, 0.0376, 0.0488, 0.0643, 0.0900, 0.1500]
          "==1": [0.0000, 0.0001, 0.0056, 0.0091, 0.0129, 0.0173, 0.0227, 0.0294, 0.0376, 0.0490, 0.0645, 0.0902, 0.1500]
          ">=2": [0.0000, 0.0001, 0.0049, 0.0082, 0.0119, 0.0162, 0.0214, 0.0276, 0.0363, 0.0469, 0.0640, 0.0883, 0.1500]
      tau_decaymode_2:
        var_dependence: tau_decaymode_2
        correction_option: "binwise"
        split_categories:
          njets:
            - "==0"
            - "==1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 0.5, 1.5, 12.5]
        var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]

    DR_SR:
      m_vis:  
      var_dependence: m_vis
      correction_option: "smoothed"
      split_categories:
        njets:
          - "==0"
          - "==1"
          - ">=2"
      split_categories_binedges:
        njets: [-0.5, 0.5, 1.5, 12.5]
      bandwidth:
        "==0": 30
        "==1": 60
        ">=2": 60
      var_bins: 
        "==0": [0.00, 48.15, 63.12, 71.85, 79.39, 87.73, 95.99, 105.43, 117.69, 135.34, 165.45, 300.00]
        "==1": [0.00, 48.00, 61.83, 70.53, 78.74, 88.07, 97.60, 109.48, 124.89, 145.77, 180.78, 300.00]
        ">=2": [0.00, 49.56, 63.32, 72.24, 81.50, 92.65, 104.18, 117.74, 135.60, 158.54, 194.66, 300.00]

      SRlike_cuts:
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      ARlike_cuts:
        lep_mt: (mt_1 > 0)
        nbtag: (nbtag == 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        nbtag: (nbtag >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))

      non_closure:
        mass_2:
          var_dependence: mass_2
          correction_option: "smoothed"
          bandwidth: 0.3
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: 
            "==0": [0.0000, 0.2000, 0.5127, 0.6201, 0.7119, 0.7964, 0.8750, 0.9575, 1.0439, 1.1318, 1.2328, 1.3652, 3.0000]
            "==1": [0.0000, 0.2000, 0.5098, 0.6187, 0.7124, 0.7954, 0.8696, 0.9556, 1.0391, 1.1279, 1.2295, 1.3584, 3.0000]
            ">=2": [0.0000, 0.2000, 0.5059, 0.6133, 0.7070, 0.7896, 0.8579, 0.9468, 1.0342, 1.1221, 1.2188, 1.3457, 3.0000]
        deltaR_ditaupair:
          var_dependence: deltaR_ditaupair
          correction_option: "smoothed"
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: 
            "==0": [0.5000, 1.4423, 1.8695, 2.1822, 2.4266, 2.6347, 2.8038, 2.9434, 3.0582, 3.1506, 3.3521, 5.0000]
            "==1": [0.5000, 1.1901, 1.5941, 1.9140, 2.1734, 2.4031, 2.6121, 2.7999, 2.9632, 3.1052, 3.3221, 5.0000]
            ">=2": [0.5000, 1.0649, 1.4358, 1.7458, 2.0092, 2.2510, 2.4699, 2.6779, 2.8644, 3.0490, 3.2758, 5.0000]
        iso_1:
          var_dependence: iso_1
          correction_option: "smoothed"
          bandwidth: 0.04
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: 
            "==0": [0.0000, 0.0001, 0.0059, 0.0093, 0.0130, 0.0175, 0.0227, 0.0291, 0.0376, 0.0488, 0.0643, 0.0900, 0.1500]
            "==1": [0.0000, 0.0001, 0.0056, 0.0091, 0.0129, 0.0173, 0.0227, 0.0294, 0.0376, 0.0490, 0.0645, 0.0902, 0.1500]
            ">=2": [0.0000, 0.0001, 0.0049, 0.0082, 0.0119, 0.0162, 0.0214, 0.0276, 0.0363, 0.0469, 0.0640, 0.0883, 0.1500]
        tau_decaymode_2:
          var_dependence: tau_decaymode_2
          correction_option: "binwise"
          split_categories:
            njets:
              - "==0"
              - "==1"
              - ">=2"
          split_categories_binedges:
            njets: [-0.5, 0.5, 1.5, 12.5]
          var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]

  ttbar:
    non_closure:
      m_vis:
        var_dependence: m_vis
        correction_option: "smoothed"
        split_categories:
          njets:
            - "<=1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 1.5, 12.5]
        var_bins:
          "<=1": [0.00, 55.91, 65.72, 72.47, 79.67, 87.06, 93.15, 102.11, 113.41, 130.68, 160.33, 300.00]
          ">=2": [0.00, 43.07, 56.64, 68.04, 77.31, 87.11, 97.20, 109.09, 123.67, 145.07, 181.74, 300.00]
      mass_2:
        var_dependence: mass_2
        bandwidth: 0.3
        correction_option: "smoothed"
        split_categories:
          njets:
            - "<=1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 1.5, 12.5]
        var_bins:
          "<=1": [0.0000, 0.2000, 0.5077, 0.6140, 0.7090, 0.7954, 0.8743, 0.9601, 1.0439, 1.1307, 1.2266, 1.3509, 3.0000]
          ">=2": [0.0000, 0.2000, 0.4910, 0.5913, 0.6955, 0.7886, 0.8638, 0.9437, 1.0275, 1.1217, 1.2236, 1.3584, 3.0000]
      deltaR_ditaupair:
        var_dependence: deltaR_ditaupair
        correction_option: "smoothed"
        split_categories:
          njets:
            - "<=1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 1.5, 12.5]
        var_bins: 
          "<=1": [0.5000, 1.6358, 2.1337, 2.4570, 2.6627, 2.8176, 2.9472, 3.0453, 3.1215, 3.2227, 3.4696, 5.0000]
          ">=2": [0.5000, 0.9863, 1.3597, 1.7024, 1.9847, 2.2288, 2.4570, 2.6923, 2.9178, 3.1080, 3.3598, 5.0000]
      iso_1:
        var_dependence: iso_1
        correction_option: "smoothed"
        split_categories:
          njets:
            - "<=1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 1.5, 12.5]
        var_bins:
          "<=1": [0.0000, 0.0001, 0.0061, 0.0095, 0.0132, 0.0174, 0.0223, 0.0296, 0.0380, 0.0488, 0.0648, 0.0922, 0.1500]
          ">=2": [0.0000, 0.0001, 0.0054, 0.0081, 0.0113, 0.0152, 0.0195, 0.0255, 0.0338, 0.0447, 0.0601, 0.0847, 0.1500]
      tau_decaymode_2:
        var_dependence: tau_decaymode_2
        correction_option: "binwise"
        split_categories:
          njets:
            - "<=1"
            - ">=2"
        split_categories_binedges:
          njets: [-0.5, 1.5, 12.5]
        var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
      