channel: mt
target_processes:
  QCD:
    split_categories:
      njets: ["==0", "==1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 30.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins:
        "==0": 10
        "==1": 5
        ">=2": 4

    SRlike_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Tight_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.05) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VLoose_2 > 0.5) && (id_tau_vsJet_Tight_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.05) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5)

    var_dependence: pt_2
    # in case of individual splitting
    var_bins:
      "==0": [30.0, 31.06, 32.33, 33.69, 35.37, 37.31, 39.73, 43.04, 47.73, 55.82, 150.0]
      "==1": [30.0, 32.33, 35.62, 40.69, 51.56, 150.0]
      ">=2": [30.0, 33.69, 39.49, 52.66, 150.0]
    fit_option:
      "==0": ["poly_1"]
      "==1": ["poly_1", "poly_2"]
      ">=2": ["poly_1"]

  Wjets:
    split_categories:
      njets: ["==0", "==1", ">=2"]
      pt_1:
        "==0": [<=37.47, '>37.47#&&#<=50.12', '>50.12#&&#<=65.82', '>65.82']
        "==1": [<=38.11, '>38.11#&&#<=50.8', '>50.8#&&#<=70.26', '>70.26']
        ">=2": [<=39.7, '>39.7#&&#<=56.33', '>56.33#&&#<=83.95', '>83.95']
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
      pt_1:
        "==0": [0.0, 37.470001220703, 50.119998931885, 65.819999694824, 1000.0]
        "==1": [0.0, 38.110000610352, 50.799999237061, 70.26000213623, 1000.0]
        ">=2": [0.0, 39.700000762939, 56.330001831055, 83.949996948242, 1000.0]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 30.0
          max: 150.0
          rounding: 2
        pt_1:
          min: 0.0
          max: 1000.0
          rounding: 2
      n_bins:
        pt_1: 4
      var_dependence_n_bins: [10, 5, 5]

    SRlike_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Tight_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 > 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VLoose_2 > 0.5) && (id_tau_vsJet_Tight_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 > 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5)

    var_dependence: pt_2
    var_bins:
      "==0":
        "<=37.47": [30.0, 30.91, 31.9, 32.99, 34.32, 35.85, 37.84, 40.3, 44.38, 52.02, 150.0]
        ">37.47#&&#<=50.12": [30.0, 30.83, 31.76, 32.79, 34.0, 35.49, 37.33, 39.8, 43.54, 51.14, 150.0]
        ">50.12#&&#<=65.82": [30.0, 30.98, 32.09, 33.29, 34.74, 36.37, 38.35, 41.21, 45.46, 52.83, 150.0]
        ">65.82": [30.0, 32.28, 34.65, 37.21, 40.28, 43.94, 48.54, 54.36, 62.74, 78.44, 150.0]
      "==1":
        "<=38.11": [30.0, 32.76, 36.25, 41.29, 51.88, 150.0]
        ">38.11#&&#<=50.8": [30.0, 32.69, 36.18, 41.2, 52.23, 150.0]
        ">50.8#&&#<=70.26": [30.0, 33.24, 37.22, 43.47, 55.58, 150.0]
        ">70.26": [30.0, 34.78, 41.68, 52.52, 71.29, 150.0]
      ">=2":
        "<=39.7": [30.0, 33.71, 38.59, 46.75, 64.03, 150.0]
        ">39.7#&&#<=56.33": [30.0, 33.33, 39.27, 48.06, 64.51, 150.0]
        ">56.33#&&#<=83.95": [30.0, 34.18, 39.84, 48.93, 66.5, 150.0]
        ">83.95": [30.0, 35.44, 43.03, 55.19, 77.0, 150.0]
    fit_option:
      "==0": ["poly_1", "poly_2"]
      "==1": ["poly_1", "poly_2"]
      ">=2": ["poly_1", "poly_2"]

  ttbar:
    split_categories:
      njets: ["<=1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 30.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [15, 10]

    SR_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Tight_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5)

    AR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VLoose_2 > 0.5) && (id_tau_vsJet_Tight_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5)

    SRlike_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Tight_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: '!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5))'

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VLoose_2 > 0.5) && (id_tau_vsJet_Tight_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: '!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5))'

    var_dependence: pt_2
    var_bins:
      "<=1": [30.0, 30.86, 31.82, 32.84, 33.87, 35.12, 36.43, 38.04, 39.75, 41.81, 44.39, 47.34, 51.99, 59.05, 71.81, 150.0]
      ">=2": [30.0, 31.77, 33.82, 36.2, 38.94, 42.51, 46.87, 53.32, 63.98, 83.61, 150.0]
    fit_option: ["poly_1", "poly_2", "poly_3"]

process_fractions:
  processes: ["QCD", "Wjets", "ttbar_J"]

  split_categories:
    njets: ["==0", "==1", ">=2"]
  split_categories_binedges:
    njets: [-0.5, 0.5, 1.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      mt_1:
        min: 0.0
        max: 70.0
        rounding: 2
    var_dependence_n_bins:
      "==0": 25
      "==1": 20
      ">=2": 15

  SR_cuts:
    had_tau_id_vs_jet: id_tau_vsJet_Tight_2 > 0.5
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5)
  AR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_VLoose_2 > 0.5) && (id_tau_vsJet_Tight_2 < 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dimuon_veto < 0.5)

  var_dependence: mt_1
  var_bins:
    "==0": [0.0, 1.97, 3.96, 6.02, 8.2, 10.5, 12.92, 15.46, 18.16, 21.05, 24.07, 27.22, 30.51, 33.88, 37.28, 40.68, 44.01, 47.32, 50.52, 53.63, 56.6, 59.44, 62.21, 64.88, 67.48, 70.0]
    "==1": [0.0, 3.47, 6.95, 10.58, 14.36, 18.15, 22.04, 26.0, 29.92, 33.94, 37.79, 41.5, 45.16, 48.71, 52.11, 55.36, 58.53, 61.57, 64.46, 67.29, 70.0]
    ">=2": [0.0, 5.1, 10.13, 15.16, 20.27, 25.33, 30.46, 35.49, 40.39, 45.1, 49.58, 53.83, 58.12, 62.2, 66.11, 70.0]
