# This is an example config containing information for the FF calculation

file_path: "/ceph/sbrommer/FFmethod/smhtt_ul/03_2023_v2"
era: "2018"
channel: "tt" # options are et, mt, tt
tree: "ntuple"

workdir_name: "full_set_v2_mc"

use_embedding: False

target_processes:
    QCD: 
        split_categories:
            njets: 
                - "==0" 
                - "==1"
                - ">=2"
        split_categories_binedges:
            njets: [-0.5,0.5,1.5,2.5]

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            had_tau_id_vs_jet_1: "id_tau_vsJet_Tight_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Tight_2 > 0.5"

        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            had_tau_id_vs_jet_1: "(id_tau_vsJet_VVLoose_1 > 0.5) && (id_tau_vsJet_Tight_1 < 0.5)"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Tight_2 > 0.5"

        var_dependence: "pt_1"
        var_bins: [30,32,35,40,48,70,100]

    QCD_subleading: 
        split_categories:
            njets: 
                - "==0" 
                - "==1"
                - ">=2"
        split_categories_binedges:
            njets: [-0.5,0.5,1.5,2.5]

        SRlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            had_tau_id_vs_jet_1: "id_tau_vsJet_Tight_1 > 0.5"
            had_tau_id_vs_jet_2: "id_tau_vsJet_Tight_2 > 0.5"

        ARlike_cuts:
            tau_pair_sign: "(q_1*q_2) > 0" 
            had_tau_id_vs_jet_1: "id_tau_vsJet_Tight_1 > 0.5"
            had_tau_id_vs_jet_2: "(id_tau_vsJet_VVLoose_2 > 0.5) && (id_tau_vsJet_Tight_2 < 0.5)"

        var_dependence: "pt_2"
        var_bins: [30,32,35,40,48,70,100]


process_fractions:
    processes: ["QCD"]

    split_categories:
        njets:
            - "==0"
            - "==1"
            - ">=2"
    split_categories_binedges:
        njets: [-0.5,0.5,1.5,2.5]

    AR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        had_tau_id_vs_jet_1: "(id_tau_vsJet_VVLoose_1 > 0.5) && (id_tau_vsJet_Tight_1 < 0.5)"
        had_tau_id_vs_jet_2: "(id_tau_vsJet_VVLoose_2 > 0.5) && (id_tau_vsJet_Tight_2 < 0.5)"

    SR_cuts:
        tau_pair_sign: "(q_1*q_2) < 0" 
        had_tau_id_vs_jet_1: "id_tau_vsJet_Tight_1 > 0.5"
        had_tau_id_vs_jet_2: "id_tau_vsJet_Tight_2 > 0.5"

    var_dependence: "m_vis"
    var_bins: [0,40,50,60,70,80,90,100,110,120,130,140,150,200]