channel: tt
processes:
  DYjets:
    samples:
      - DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - J
      - T
      - L
  ST:
    samples:
      - ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8_RunIISummer20UL18NanoAODv9-106X
      - ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8_RunIISummer20UL18NanoAODv9-106X
      - ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
      - ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - J
      - T
      - L
  Wjets:
    samples:
      - WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - all
  data:
    samples:
      - Tau_Run2018A-UL2018
      - Tau_Run2018B-UL2018
      - Tau_Run2018C-UL2018
      - Tau_Run2018D-UL2018
    tau_gen_modes:
      - all
  diboson:
    samples:
      - WW_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X
      - WZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X
      - ZZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - J
      - T
      - L
  embedding:
    samples:
      - TauEmbedding-TauTauFinalState_Run2018A-UL2018
      - TauEmbedding-TauTauFinalState_Run2018B-UL2018
      - TauEmbedding-TauTauFinalState_Run2018C-UL2018
      - TauEmbedding-TauTauFinalState_Run2018D-UL2018
    tau_gen_modes:
      - all
  ttbar:
    samples:
      - TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
      - TTToHadronic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
      - TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - J
      - T
      - L
event_selection:
  double_trigger: (trg_double_tau35_tightiso_tightid > 0.5) || (trg_double_tau35_mediumiso_hps > 0.5) || (trg_double_tau40_mediumiso_tightid > 0.5) || (trg_double_tau40_tightiso > 0.5)
  had_tau_decay_mode_1: (tau_decaymode_1 == 0) || (tau_decaymode_1 == 1) || (tau_decaymode_1 == 10) || (tau_decaymode_1 == 11)
  had_tau_decay_mode_2: (tau_decaymode_2 == 0) || (tau_decaymode_2 == 1) || (tau_decaymode_2 == 10) || (tau_decaymode_2 == 11)
  had_tau_eta: (abs(eta_1) < 2.3) && (abs(eta_2) < 2.3)
  had_tau_id_vs_ele: (id_tau_vsEle_VVLoose_1 > 0.5) && (id_tau_vsEle_VVLoose_2 > 0.5)
  had_tau_id_vs_mu: (id_tau_vsMu_VLoose_1 > 0.5) && (id_tau_vsMu_VLoose_2 > 0.5)
  had_tau_pt: (pt_1 > 40) && (pt_2 > 40)
mc_weights:
  Top_pt_reweighting: topPtReweightWeight
  Z_pt_reweighting: ZPtMassReweightWeight
  generator:
    stitching:
      - DYjets
      - Wjets
  had_tau_id_vs_ele_1: (gen_match_1==5) * ((id_tau_vsEle_VVLoose_1>0.5)*id_wgt_tau_vsEle_VVLoose_1 + (id_tau_vsEle_VVLoose_1<0.5)) + (gen_match_1!=5)
  had_tau_id_vs_ele_2: (gen_match_2==5) * ((id_tau_vsEle_VVLoose_2>0.5)*id_wgt_tau_vsEle_VVLoose_2 + (id_tau_vsEle_VVLoose_2<0.5)) + (gen_match_2!=5)
  had_tau_id_vs_mu_1: (gen_match_1==5) * ((id_tau_vsMu_VLoose_1>0.5)*id_wgt_tau_vsMu_VLoose_1 + (id_tau_vsMu_VLoose_1<0.5)) + (gen_match_1!=5)
  had_tau_id_vs_mu_2: (gen_match_2==5) * ((id_tau_vsMu_VLoose_2>0.5)*id_wgt_tau_vsMu_VLoose_2 + (id_tau_vsMu_VLoose_2<0.5)) + (gen_match_2!=5)
  lumi: ""
  pileup: puweight
emb_weights:
  double_trigger: emb_trg_wgt_1 * emb_trg_wgt_2
  generator: emb_genweight * emb_idsel_wgt_1 * emb_idsel_wgt_2 * emb_triggersel_wgt
wps:
  tau_vs_jet:
    wgt:
      - Medium
      - Tight
      - VTight
    wp:
      - VVLoose
      - VLoose
      - Loose
      - Medium
      - Tight
      - VTight
