# This is an example config containing information for the FF corrections

workdir_name: "full_set_v1"
era: "2018"
channel: "tt" # options are et, mt, tt

generate_json: True

target_process:
    QCD:
        non_closure:
            lep_pt:
                var_dependence: "pt_1"
                var_bins: [30,35,40,45,50,55,60,70,80,100]
        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,30,80,90,100,120,140,160,180,250]
