# This is an example config containing information for the preselection

ntuple_path: "root://cmsxrootd-kit.gridka.de//store/user/sbrommer/CROWN/ntuples/tautau_2018_v4/CROWNRun"
# ntuple_path: "/ceph/nshadskiy/nmssm_ul/nmssm_02_2023_v2/ntuples"
era: "2018"
channel: "tt"
tree: "ntuple"

output_path: "/ceph/sbrommer/FFmethod/smhtt_ul/03_2023_v2"

processes:
    DYjets:
        tau_gen_modes:
            - "J"
            - "T"
            - "L"
        samples:
            - "DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
    diboson:
        tau_gen_modes:
            - "J"
            - "T"
            - "L"
        samples:
            - WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
            - WW_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X
            - WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIISummer20UL18NanoAODv9-106X
            - WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8_RunIISummer20UL18NanoAODv9-106X
            - WZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X
            - ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8_RunIISummer20UL18NanoAODv9-106X
            - ZZTo4L_TuneCP5_13TeV_powheg_pythia8_RunIISummer20UL18NanoAODv9-106X
            - ZZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X
    ttbar:
        tau_gen_modes:
            - "J"
            - "T"
            - "L"
        samples:
            - "TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "TTToHadronic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
    Wjets:
        tau_gen_modes:
            - "all"
        samples:
            - "WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
    embedding:
        tau_gen_modes:
            - "all"
        samples:
            - "TauEmbedding-TauTauFinalState_Run2018A-UL2018"
            - "TauEmbedding-TauTauFinalState_Run2018B-UL2018"
            - "TauEmbedding-TauTauFinalState_Run2018C-UL2018"
            - "TauEmbedding-TauTauFinalState_Run2018D-UL2018"
    data:
        tau_gen_modes:
            - "all"
        samples:
            - "Tau_Run2018A-UL2018"
            - "Tau_Run2018B-UL2018"
            - "Tau_Run2018C-UL2018"
            - "Tau_Run2018D-UL2018"

event_selection:
    had_tau_pt: ">40"
    had_tau_eta: "<2.3"
    had_tau_decay_mode: ["0","1","10","11"] # has to be a list
    had_tau_id_vs_ele: "VVLoose"
    had_tau_id_vs_mu: "VLoose"
    # lep_iso: "<0.15"
    trigger: True

mc_weights:
    - "generator"
    - "lumi"
    - "pileup"
    - "had_tau_id_vs_ele"
    - "had_tau_id_vs_mu"
    - "Z_pt_reweight"
    - "Top_pt_reweight"
    - "trigger"

emb_weights:
    - "generator"
    - "trigger"