ntuple_path: "root://cmsdcache-kit-disk.gridka.de//store/user/sgiappic/CROWN/ntuples/htt_260520_2022-23/CROWNRun/" #root://cmsdcache-kit-disk.gridka.de//store/user
output_path: "/ceph/sgiappic/CMS_FF/260520/"
#friends: 
file_path: "/ceph/sgiappic/CMS_FF/260520/"

workdir_name: htt_260520

era: '2023postBPix'
tree: ntuple
nanoAOD_version: "nanoAOD_v12"

tau_vs_jet_wps:
  - VVVLoose
  - Medium
tau_vs_jet_wgt_wps:
  - Medium

use_embedding: false
use_center_of_mass_bins: true
