templates:
  split_schemes:
    3j:
      split_categories:
        njets: ["==0", "==1", ">=2"]
      split_categories_binedges:
        njets: [-0.5, 0.5, 1.5, 22.5]
      correction_option:
        "==0": "smoothed"
        "==1": "smoothed"
        ">=2": "smoothed"
      bandwidth:
        "==0": 1.0
        "==1": 1.0
        ">=2": 1.0
    2j: &2j_split
      split_categories:
        njets: ["==0", ">=1"]
      split_categories_binedges:
        njets: [-0.5, 0.5, 22.5]
      correction_option:
        "==0": "smoothed"
        ">=1": "smoothed"
      bandwidth:
        "==0": 1.0
        ">=1": 1.0
  var_dependence_n_bins:
    QCD:
      equipopulated_binning_options: &QCD_var_dependence_n_bins
        var_dependence_n_bins: [15, 10]
    QCD_subleading:
      equipopulated_binning_options: &QCD_subleading_var_dependence_n_bins
        var_dependence_n_bins: [15, 10]
  variables:
    deltaR_ditaupair: &deltaR_ditaupair
      var_dependence: deltaR_ditaupair
      equipopulated_binning_options: &deltaR_ditaupair__eq_bin_opt
        variable_config:
          deltaR_ditaupair:
            min: 0.5
            max: 5.0
            rounding: 4
      correction_option: "smoothed"
    mass_1: &mass_1
      var_dependence: mass_1
      equipopulated_binning_options: &mass_1__eq_bin_opt
        variable_config:
          mass_1:
            min: 0.14
            max: 2.0
            rounding: 2
        add_left: [0.0]
      correction_option: "smoothed"
    mass_2: &mass_2
      var_dependence: mass_2
      equipopulated_binning_options: &mass_2__eq_bin_opt
        variable_config:
          mass_2:
            min: 0.14
            max: 2.0
            rounding: 2
        add_left: [0.0]
      correction_option: "smoothed"
    pt_1: &pt_1
      var_dependence: pt_1
      equipopulated_binning_options: &pt_1__eq_bin_opt
        variable_config:
          pt_1:
            min: 35.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    pt_2: &pt_2
      var_dependence: pt_2
      equipopulated_binning_options: &pt_2__eq_bin_opt
        variable_config:
          pt_2:
            min: 35.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    pt_tt: &pt_tt
      var_dependence: pt_tt
      equipopulated_binning_options: &pt_tt__eq_bin_opt
        variable_config:
          pt_tt:
            min: 0.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    eta_1: &eta_1
      var_dependence: eta_1
      equipopulated_binning_options: &eta_1__eq_bin_opt
        variable_config:
          eta_1:
            min: -2.3
            max: 2.3
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 0.2
    eta_2: &eta_2
      var_dependence: eta_2
      equipopulated_binning_options: &eta_2__eq_bin_opt
        variable_config:
          eta_2:
            min: -2.3
            max: 2.3
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 0.2
    jpt_1:
      var_dependence: jpt_1
      equipopulated_binning_options:
        variable_config:
          jpt_1:
            min: 30.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    jpt_2:
      var_dependence: jpt_2
      equipopulated_binning_options:
        variable_config:
          jpt_2:
            min: 30.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    met: &met
      var_dependence: met
      equipopulated_binning_options: &met__eq_bin_opt
        variable_config:
          met:
            min: 0.0
            max: 150.0
            rounding: 6
      correction_option: "smoothed"
      bandwidth: 1.0
    m_vis: &m_vis
      var_dependence: m_vis
      equipopulated_binning_options: &m_vis__eq_bin_opt
        variable_config:
          m_vis:
            min: 15.0
            max: 250.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 30
    tau_decaymode_1: &tau_decaymode_1
      var_dependence: tau_decaymode_1
      correction_option: "binwise"
      bandwidth: 1.0
      var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
    tau_decaymode_2: &tau_decaymode_2
      var_dependence: tau_decaymode_2
      correction_option: "binwise"
      bandwidth: 1.0
      var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]


channel: tt
target_processes:
  QCD:
    non_closure:
      tau_decaymode_1:
        <<: [*tau_decaymode_1, *2j_split]
      mass_1:
        <<: [*mass_1, *2j_split]
        equipopulated_binning_options:
          <<: [*mass_1__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 0.2
        var_bins:
          "==0": [0.0, 0.14, 0.46, 0.53, 0.6, 0.67, 0.74, 0.8, 0.87, 0.93, 1.0, 1.06, 1.13, 1.21, 1.29, 1.41, 2.0]
          ">=1": [0.0, 0.14, 0.5, 0.6, 0.71, 0.81, 0.91, 1.01, 1.11, 1.22, 1.36, 2.0]
      eta_1:
        <<: [*eta_1, *2j_split]
        equipopulated_binning_options:
          <<: [*eta_1__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 0.5
        var_bins:
          "==0": [-2.3, -1.73, -1.37, -1.08, -0.83, -0.59, -0.35, -0.11, 0.11, 0.34, 0.57, 0.8, 1.03, 1.3, 1.68, 2.3]
          ">=1": [-2.3, -1.66, -1.18, -0.79, -0.38, 0.01, 0.4, 0.77, 1.13, 1.6, 2.3]
      pt_1:
        <<: [*pt_1, *2j_split]
        equipopulated_binning_options:
          <<: [*pt_1__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 5.0
        var_bins:
          "==0": [35.0, 43.95, 45.86, 47.47, 49.05, 50.67, 52.36, 54.13, 56.13, 58.3, 60.85, 64.0, 68.06, 73.69, 83.39, 150.0]
          ">=1": [35.0, 46.56, 50.38, 54.0, 57.84, 62.02, 67.3, 73.88, 83.13, 98.42, 150.0]
      # jpt_1:
      #   <<: [*jpt_1, *2j_split]
      #   equipopulated_binning_options:
      #     <<: [*jpt_1__eq_bin_opt, *QCD_var_dependence_n_bins]
      #   correction_option: ["skip", "smoothed"]
      #   bandwidth: 5.0
      #   var_bins:
      #     "==0": [30.0, 150.0]
      #     ">=1": [30.0, 32.93, 36.45, 40.74, 45.95, 52.32, 59.24, 68.65, 81.75, 102.64, 150.0]
      # jpt_2:
      #   <<: [*jpt_2, *2j_split]
      #   equipopulated_binning_options:
      #     <<: [*jpt_2__eq_bin_opt, *QCD_var_dependence_n_bins]
      #   correction_option: ["skip", "smoothed"]
      #   bandwidth: 5.0
      #   var_bins:
      #     "==0": [30.0, 150.0]
      #     ">=1": [30.0, 31.94, 34.07, 36.81, 39.97, 43.87, 49.31, 55.41, 63.93, 78.05, 150.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *2j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 1.0
        var_bins:
          "==0": [0.5, 2.7878, 2.9261, 3.0036, 3.0579, 3.0987, 3.1323, 3.1681, 3.2173, 3.2809, 3.3606, 3.456, 3.5786, 3.7487, 4.012, 5.0]
          ">=1": [0.5, 1.5482, 2.1315, 2.4583, 2.6865, 2.8706, 3.0213, 3.1676, 3.3738, 3.7192, 5.0]
      met:
        <<: [*met, *2j_split]
        equipopulated_binning_options:
          <<: [*met__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 10.0
        var_bins:
          "==0": [0.0, 6.18468, 8.903164, 11.230348, 13.339906, 15.487691, 17.623348, 19.845137, 22.274714, 24.73904, 27.633055, 30.923656, 35.17112, 40.940174, 50.759705, 150.0]
          ">=1": [0.0, 10.237087, 14.966271, 19.278305, 23.43454, 27.941818, 32.928192, 38.969864, 46.500366, 59.051228, 150.0]
      m_vis:
        <<: [*m_vis, *2j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth: 25.0
        var_bins:
          "==0": [15.0, 90.46, 95.55, 99.93, 104.28, 108.84, 113.57, 118.9, 124.79, 131.74, 139.63, 149.41, 161.89, 178.04, 203.0, 250.0]
          ">=1": [15.0, 74.99, 91.92, 102.61, 112.95, 124.46, 136.72, 152.35, 172.62, 200.49, 250.0]

    DR_SR:
      <<: [*pt_tt, *2j_split]
      equipopulated_binning_options:
        <<: [*pt_tt__eq_bin_opt, *QCD_var_dependence_n_bins]
      bandwidth: 20.0
      var_bins:
        "==0": [0.0, 6.04, 8.85, 11.23, 13.4, 15.55, 17.71, 19.91, 22.29, 24.86, 27.74, 31.16, 35.35, 41.03, 50.74, 150.0]
        ">=1": [0.0, 20.47, 29.16, 36.2, 43.07, 50.21, 58.1, 67.56, 80.77, 100.24, 150.0]

      SRlike_cuts:
        had_tau_id_vs_jet_2: (id_tau_vsJet_Medium_2 < 0.5)
      ARlike_cuts:
        had_tau_id_vs_jet_2: (id_tau_vsJet_Medium_2 < 0.5)
      AR_SR_cuts:
        tau_pair_sign: (q_1*q_2) < 0

      non_closure:
        tau_decaymode_1:
          <<: [*tau_decaymode_1, *2j_split]

  QCD_subleading:
    non_closure:
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *2j_split]
      mass_2:
        <<: [*mass_2, *2j_split]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 0.2
        var_bins:
          "==0": [0.0, 0.14, 0.45, 0.52, 0.59, 0.65, 0.71, 0.77, 0.83, 0.89, 0.95, 1.01, 1.08, 1.16, 1.25, 1.37, 2.0]
          ">=1": [0.0, 0.14, 0.49, 0.59, 0.68, 0.77, 0.85, 0.94, 1.04, 1.15, 1.31, 2.0]
      eta_2:
        <<: [*eta_2, *2j_split]
        equipopulated_binning_options:
          <<: [*eta_2__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 0.5
        var_bins:
          "==0": [-2.3, -1.79, -1.48, -1.17, -0.9, -0.63, -0.38, -0.13, 0.11, 0.36, 0.59, 0.84, 1.1, 1.38, 1.75, 2.3]
          ">=1": [-2.3, -1.63, -1.17, -0.79, -0.4, -0.03, 0.34, 0.73, 1.09, 1.56, 2.3]
      pt_2:
        <<: [*pt_2, *2j_split]
        equipopulated_binning_options:
          <<: [*pt_2__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 5.0
        var_bins:
          "==0": [35.0, 40.59, 41.21, 41.89, 42.61, 43.39, 44.25, 45.19, 46.28, 47.56, 49.12, 51.01, 53.62, 57.61, 65.25, 150.0]
          ">=1": [35.0, 40.99, 42.12, 43.4, 44.85, 46.58, 48.69, 51.73, 56.14, 64.67, 150.0]
      # jpt_1:
      #   <<: [*jpt_1, *2j_split]
      #   equipopulated_binning_options:
      #     <<: [*jpt_1__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
      #   correction_option: ["skip", "smoothed"]
      #   bandwidth: 5.0
      #   var_bins:
      #     "==0": [30.0, 150.0]
      #     ">=1": [30.0, 32.93, 36.45, 40.74, 45.95, 52.32, 59.24, 68.65, 81.75, 102.64, 150.0]
      # jpt_2:
      #   <<: [*jpt_2, *2j_split]
      #   equipopulated_binning_options:
      #     <<: [*jpt_2__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
      #   correction_option: ["skip", "smoothed"]
      #   bandwidth: 5.0
      #   var_bins:
      #     "==0": [30.0, 150.0]
      #     ">=1": [30.0, 31.94, 34.07, 36.81, 39.97, 43.87, 49.31, 55.41, 63.93, 78.05, 150.0]
      deltaR_ditaupair:
        <<: [*deltaR_ditaupair, *2j_split]
        equipopulated_binning_options:
          <<: [*deltaR_ditaupair__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 1.0
        var_bins:
          "==0": [0.5, 2.7878, 2.9261, 3.0036, 3.0579, 3.0987, 3.1323, 3.1681, 3.2173, 3.2809, 3.3606, 3.456, 3.5786, 3.7487, 4.012, 5.0]
          ">=1": [0.5, 1.5482, 2.1315, 2.4583, 2.6865, 2.8706, 3.0213, 3.1676, 3.3738, 3.7192, 5.0]
      met:
        <<: [*met, *2j_split]
        equipopulated_binning_options:
          <<: [*met__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 10.0
        var_bins:
          "==0": [0.0, 6.18468, 8.903164, 11.230348, 13.339906, 15.487691, 17.623348, 19.845137, 22.274714, 24.73904, 27.633055, 30.923656, 35.17112, 40.940174, 50.759705, 150.0]
          ">=1": [0.0, 10.237087, 14.966271, 19.278305, 23.43454, 27.941818, 32.928192, 38.969864, 46.500366, 59.051228, 150.0]
      m_vis:
        <<: [*m_vis, *2j_split]
        equipopulated_binning_options:
          <<: [*m_vis__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
        bandwidth: 25.0
        var_bins:
          "==0": [15.0, 90.46, 95.55, 99.93, 104.28, 108.84, 113.57, 118.9, 124.79, 131.74, 139.63, 149.41, 161.89, 178.04, 203.0, 250.0]
          ">=1": [15.0, 74.99, 91.92, 102.61, 112.95, 124.46, 136.72, 152.35, 172.62, 200.49, 250.0]

    DR_SR:
      <<: [*pt_tt, *2j_split]
      equipopulated_binning_options:
        <<: [*pt_tt__eq_bin_opt, *QCD_subleading_var_dependence_n_bins]
      bandwidth: 20.0
      var_bins:
        "==0": [0.0, 5.93, 8.66, 10.94, 13.1, 15.16, 17.26, 19.43, 21.75, 24.27, 27.06, 30.33, 34.41, 39.96, 49.5, 150.0]
        ">=1": [0.0, 20.2, 28.64, 35.63, 42.37, 49.89, 58.0, 67.66, 80.3, 99.86, 150.0]

      SRlike_cuts:
        had_tau_id_vs_jet_1: (id_tau_vsJet_Medium_1 < 0.5)
      ARlike_cuts:
        had_tau_id_vs_jet_1: (id_tau_vsJet_Medium_1 < 0.5)
      AR_SR_cuts:
        tau_pair_sign: (q_1*q_2) < 0

      non_closure:
        tau_decaymode_2:
          <<: [*tau_decaymode_2, *2j_split]
