channel: et
target_processes:
  QCD:
    split_categories:
      njets: ["==0", ">=1"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [15, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.02) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.02) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    var_dependence: pt_2
    var_bins:
      "==0": [20.0, 21.37, 22.78, 24.12, 25.69, 27.3, 28.88, 30.57, 32.45, 34.41, 36.92, 39.56, 43.19, 47.73, 55.48, 150.0]
      ">=1": [20.0, 21.39, 23.02, 25.01, 27.24, 29.78, 33.12, 37.42, 43.38, 57.13, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 10.0

  Wjets:
    split_categories:
      njets: ["==0", ">=1"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [15, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    var_dependence: pt_2
    var_bins:
      "==0": [20.0, 20.91, 21.91, 22.94, 24.06, 25.3, 26.66, 28.19, 29.89, 31.81, 34.18, 36.95, 40.63, 46.08, 56.71, 150.0]
      ">=1": [20.0, 22.03, 24.22, 26.85, 29.81, 33.1, 37.41, 43.36, 51.86, 69.08, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 10.0

  ttbar:
    split_categories:
      njets: ["<=1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [15, 20]

    SR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    AR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    var_dependence: pt_2
    var_bins:
      "<=1": [20.0, 21.33, 22.72, 24.02, 25.77, 27.25, 28.96, 31.33, 34.54, 37.11, 40.4, 44.85, 52.58, 64.26, 76.26, 150.0]
      ">=2": [20.0, 21.18, 22.87, 24.11, 26.17, 27.99, 29.64, 31.82, 33.29, 34.68, 37.09, 40.26, 43.78, 47.05, 50.58, 55.58, 61.66, 70.99, 83.42, 104.8, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 10.0

process_fractions:
  processes: ["QCD", "Wjets", "ttbar_J"]

  split_categories:
    njets: ["==0", ">=1"]
  split_categories_binedges:
    njets: [-0.5, 0.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      mt_1:
        min: 0.0
        max: 70.0
        rounding: 2
    var_dependence_n_bins: [15, 10]

  SR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
  AR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

  var_dependence: mt_1
  var_bins:
    "==0": [0.0, 6.44, 12.9, 19.09, 24.97, 30.5, 35.62, 40.38, 44.81, 48.97, 52.89, 56.64, 60.19, 63.56, 66.83, 70.0]
    ">=1": [0.0, 8.78, 17.53, 25.89, 33.69, 40.91, 47.56, 53.69, 59.42, 64.84, 70.0]
