channel: mt
target_processes:
  QCD:
    split_categories:
      njets: ["==0", "==1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [40, 25, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    var_dependence: pt_2
    # in case of individual splitting
    var_bins:
      "==0": [20.0, 20.32, 20.65, 20.99, 21.34, 21.71, 22.07, 22.43, 22.82, 23.22, 23.64, 24.08, 24.51, 24.96, 25.43, 25.89, 26.4, 26.93, 27.46, 28.0, 28.62, 29.22, 29.85, 30.53, 31.21, 31.96, 32.75, 33.6, 34.53, 35.51, 36.57, 37.7, 39.08, 40.63, 42.52, 44.74, 47.51, 51.12, 56.56, 66.35, 150.0]
      "==1": [20.0, 20.43, 20.91, 21.38, 21.89, 22.46, 23.03, 23.66, 24.32, 25.02, 25.74, 26.6, 27.47, 28.5, 29.64, 30.83, 32.18, 33.85, 35.7, 37.99, 40.71, 44.04, 48.95, 56.33, 70.33, 150.0]
      ">=2": [20.0, 21.44, 22.98, 24.76, 27.01, 29.72, 32.91, 37.42, 44.45, 57.09, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 20.0

  Wjets:
    split_categories:
      njets: ["==0", "==1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [40, 25, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    var_dependence: pt_2
    var_bins:
      "==0": [20.0, 20.28, 20.56, 20.86, 21.16, 21.48, 21.8, 22.12, 22.46, 22.81, 23.18, 23.56, 23.95, 24.35, 24.77, 25.21, 25.68, 26.16, 26.66, 27.18, 27.72, 28.29, 28.9, 29.54, 30.23, 30.99, 31.77, 32.57, 33.42, 34.4, 35.49, 36.7, 38.07, 39.65, 41.53, 43.78, 46.71, 50.7, 56.8, 68.5, 150.0]
      "==1": [20.0, 20.65, 21.37, 22.11, 22.85, 23.65, 24.48, 25.36, 26.31, 27.3, 28.33, 29.48, 30.6, 31.94, 33.41, 35.08, 36.96, 38.97, 41.33, 44.15, 47.58, 51.83, 57.85, 66.65, 82.62, 150.0]
      ">=2": [20.0, 22.03, 24.39, 27.03, 30.16, 33.75, 38.52, 45.22, 55.32, 74.08, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 20.0

  ttbar:
    split_categories:
      njets: ["<=1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [30, 30]

    SR_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Medium_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    AR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    SRlike_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Medium_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: '!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5))'

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: '!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5))'

    var_dependence: pt_2
    var_bins:
      "<=1": [20.0, 20.44, 20.91, 21.4, 21.91, 22.47, 23.07, 23.71, 24.31, 25.01, 25.72, 26.52, 27.28, 28.06, 28.93, 29.85, 30.9, 31.93, 33.15, 34.36, 35.8, 37.4, 39.09, 41.06, 43.21, 45.8, 48.99, 52.84, 59.68, 72.16, 150.0]
      ">=2": [20.0, 20.63, 21.1, 21.77, 22.39, 23.1, 23.73, 24.48, 25.26, 26.04, 26.97, 27.92, 28.72, 29.81, 30.93, 32.09, 33.39, 34.8, 36.26, 38.06, 39.55, 41.53, 44.47, 47.56, 50.75, 54.75, 59.82, 66.95, 76.71, 93.69, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 20.0

process_fractions:
  processes: ["QCD", "Wjets", "ttbar_J"]

  split_categories:
    njets: ["==0", "==1", ">=2"]
  split_categories_binedges:
    njets: [-0.5, 0.5, 1.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      mt_1:
        min: 0.0
        max: 70.0
        rounding: 2
    var_dependence_n_bins: [40, 25, 10]

  SR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: (iso_1 < 0.15)
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)
  AR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: (iso_1 < 0.15)
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

  var_dependence: mt_1
  var_bins:
    "==0": [0.0, 1.99, 3.97, 5.97, 7.99, 10.05, 12.12, 14.24, 16.36, 18.52, 20.7, 22.84, 25.01, 27.16, 29.29, 31.39, 33.48, 35.48, 37.45, 39.36, 41.26, 43.1, 44.9, 46.64, 48.34, 49.99, 51.57, 53.11, 54.61, 56.06, 57.48, 58.87, 60.22, 61.53, 62.81, 64.06, 65.3, 66.5, 67.69, 68.85, 70.0]
    "==1": [0.0, 3.08, 6.16, 9.34, 12.56, 15.82, 19.11, 22.46, 25.8, 29.12, 32.4, 35.59, 38.72, 41.7, 44.54, 47.31, 49.95, 52.52, 55.0, 57.34, 59.63, 61.83, 63.95, 65.99, 68.02, 70.0]
    ">=2": [0.0, 8.01, 15.97, 23.94, 31.7, 39.2, 46.18, 52.77, 58.85, 64.55, 70.0]
