channel: et
target_processes:
  QCD:
    split_categories:
      njets: ["==0", "==1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [40, 25, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    var_dependence: pt_2
    var_bins:
      "==0": [20.0, 20.51, 21.02, 21.5, 22.03, 22.57, 23.12, 23.66, 24.23, 24.79, 25.39, 25.97, 26.58, 27.21, 27.83, 28.46, 29.11, 29.76, 30.42, 31.08, 31.79, 32.49, 33.17, 33.93, 34.74, 35.64, 36.61, 37.58, 38.57, 39.59, 40.84, 42.21, 43.55, 45.18, 47.1, 49.26, 52.2, 56.02, 61.49, 71.74, 150.0]
      "==1": [20.0, 20.52, 21.09, 21.7, 22.38, 23.04, 23.72, 24.51, 25.31, 26.19, 27.07, 28.1, 29.19, 30.29, 31.45, 32.78, 34.24, 35.97, 38.09, 40.55, 43.31, 47.11, 52.25, 59.92, 75.1, 150.0]
      ">=2": [20.0, 21.47, 23.38, 25.66, 28.27, 31.29, 34.86, 40.33, 47.97, 62.42, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 20.0

  Wjets:
    split_categories:
      njets: ["==0", "==1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [40, 25, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    var_dependence: pt_2
    var_bins:
      "==0": [20.0, 20.33, 20.67, 21.02, 21.39, 21.77, 22.15, 22.53, 22.92, 23.33, 23.75, 24.19, 24.65, 25.11, 25.58, 26.09, 26.61, 27.17, 27.74, 28.35, 28.97, 29.62, 30.28, 30.98, 31.74, 32.58, 33.46, 34.38, 35.37, 36.47, 37.67, 39.02, 40.51, 42.28, 44.31, 46.77, 50.02, 54.63, 61.42, 74.07, 150.0]
      "==1": [20.0, 20.73, 21.52, 22.31, 23.11, 23.98, 24.92, 25.91, 26.95, 28.0, 29.14, 30.37, 31.58, 33.01, 34.57, 36.25, 38.17, 40.34, 42.97, 45.83, 49.39, 54.19, 60.8, 70.24, 85.96, 150.0]
      ">=2": [20.0, 22.38, 24.94, 27.96, 31.35, 35.24, 40.52, 47.4, 58.12, 78.22, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 20.0

  ttbar:
    split_categories:
      njets: ["<=1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [30, 30]

    SR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    AR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: (iso_1 < 0.15)
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    var_dependence: pt_2
    var_bins:
      "<=1": [20.0, 20.53, 21.12, 21.74, 22.45, 23.16, 23.84, 24.56, 25.36, 26.3, 27.12, 28.06, 29.17, 30.19, 31.35, 32.62, 33.81, 35.1, 36.6, 38.28, 40.07, 41.86, 43.94, 46.42, 49.06, 51.86, 55.23, 60.29, 67.86, 84.24, 150.0]
      ">=2": [20.0, 20.61, 21.26, 21.97, 22.75, 23.5, 24.28, 25.0, 26.0, 26.94, 27.84, 28.9, 29.9, 31.09, 32.27, 33.14, 34.47, 36.14, 37.88, 39.91, 42.23, 44.88, 47.66, 50.45, 54.68, 59.22, 65.01, 72.94, 83.69, 106.0, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 20.0

process_fractions:
  processes: ["QCD", "Wjets", "ttbar_J"]

  split_categories:
    njets: ["==0", "==1", ">=2"]
  split_categories_binedges:
    njets: [-0.5, 0.5, 1.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      mt_1:
        min: 0.0
        max: 70.0
        rounding: 2
    var_dependence_n_bins: [40, 25, 10]

  SR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: (iso_1 < 0.15)
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
  AR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: (iso_1 < 0.15)
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

  var_dependence: mt_1
  var_bins:
    "==0": [0.0, 2.43, 4.83, 7.22, 9.64, 12.07, 14.42, 16.74, 19.03, 21.28, 23.46, 25.63, 27.74, 29.77, 31.75, 33.68, 35.55, 37.39, 39.17, 40.88, 42.57, 44.2, 45.82, 47.39, 48.9, 50.4, 51.87, 53.33, 54.75, 56.14, 57.51, 58.85, 60.16, 61.45, 62.71, 63.97, 65.2, 66.41, 67.62, 68.81, 70.0]
    "==1": [0.0, 3.53, 7.08, 10.57, 14.14, 17.62, 21.06, 24.42, 27.7, 30.85, 33.9, 36.88, 39.74, 42.5, 45.18, 47.78, 50.28, 52.71, 55.04, 57.32, 59.55, 61.72, 63.86, 65.96, 68.0, 70.0]
    ">=2": [0.0, 8.69, 17.25, 25.37, 33.12, 40.27, 46.99, 53.2, 59.08, 64.63, 70.0]
