channel: mt
target_processes:
  QCD:
    split_categories:
      njets: ["==0", ">=1"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [15, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.05) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.05) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    var_dependence: pt_2
    # in case of individual splitting
    var_bins:
      "==0": [20.0, 20.94, 21.89, 22.89, 24.05, 25.28, 26.6, 28.11, 29.83, 31.72, 33.91, 36.46, 39.7, 44.43, 52.53, 150.0]
      ">=1": [20.0, 21.11, 22.52, 24.11, 25.86, 28.22, 31.09, 35.01, 41.41, 52.73, 150.0]
    fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    #fit_option: "smoothed"
    bandwidth: 10.0

  Wjets:
    split_categories:
      njets: ["==0", ">=1"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [15, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 > 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 > 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    var_dependence: pt_2
    var_bins:
      "==0": [20.0, 20.76, 21.59, 22.47, 23.44, 24.5, 25.7, 27.02, 28.52, 30.27, 32.31, 34.81, 38.13, 43.08, 52.56, 150.0]
      ">=1": [20.0, 21.82, 23.87, 26.17, 28.87, 31.99, 36.01, 41.47, 49.73, 65.36, 150.0]
    fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    #fit_option: "smoothed"
    bandwidth: 10.0

  ttbar:
    split_categories:
      njets: ["<=1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [15, 20]

    SR_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Medium_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    AR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    SRlike_cuts:
      had_tau_id_vs_jet: id_tau_vsJet_Medium_2 > 0.5
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: '!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5))'

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: '!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5))'

    var_dependence: pt_2
    var_bins:
      "<=1": [20.0, 21.33, 22.82, 24.12, 25.69, 27.22, 29.54, 31.44, 33.82, 36.47, 40.36, 43.88, 49.38, 57.19, 74.25, 150.0]
      ">=2": [20.0, 20.91, 22.3, 23.47, 24.93, 26.17, 27.75, 29.51, 31.56, 34.45, 36.79, 39.55, 42.55, 46.59, 50.37, 55.28, 62.12, 71.36, 81.17, 98.41, 150.0]
    fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    #fit_option: "smoothed"
    bandwidth: 10.0

process_fractions:
  processes: ["QCD", "Wjets", "ttbar_J"]

  split_categories:
    njets: ["==0", ">=1"]
  split_categories_binedges:
    njets: [-0.5, 0.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      mt_1:
        min: 0.0
        max: 70.0
        rounding: 2
    var_dependence_n_bins: [15, 10]

  SR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)
  AR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

  var_dependence: mt_1
  var_bins:
    "==0": [0.0, 4.99, 10.15, 15.58, 21.22, 26.94, 32.6, 37.97, 43.03, 47.77, 52.16, 56.2, 59.97, 63.48, 66.82, 70.0]
    ">=1": [0.0, 7.39, 15.06, 23.11, 31.22, 39.08, 46.3, 52.97, 59.08, 64.71, 70.0]
