# This is a example config containing information for the preselection

ntuple_path: "/storage/gridka-nrg/nshadskiy/CROWN/ntuples/ff_ntuple_mt/CROWNRun"
era: "2018"

channel: "mt" # options are et, mt, tt
processes:
    DYjets:
        tau_gen_modes:
            - "J"
            - "T"
            - "L"
        samples:
            - "DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
    diboson:
        tau_gen_modes:
            - "J"
            - "T"
            - "L"
        samples:
            - "ZZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X" 
            - "WW_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "WZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X"
    ttbar:
        tau_gen_modes:
            - "J"
            - "T"
            - "L"
        samples:
            - "TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "TTToHadronic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
            - "TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X"
    Wjets:
        tau_gen_modes:
            - "all"
        samples:
            - "WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X"
    embedding:
        tau_gen_modes:
            - "all"
        samples:
            - "TauEmbedding-MuTauFinalState_Run2018A-UL2018"
            - "TauEmbedding-MuTauFinalState_Run2018B-UL2018"
            - "TauEmbedding-MuTauFinalState_Run2018C-UL2018"
            - "TauEmbedding-MuTauFinalState_Run2018D-UL2018"
    data:
        tau_gen_modes:
            - "all"
        samples:
            - "SingleMuon_Run2018A-UL2018"
            - "SingleMuon_Run2018B-UL2018"
            - "SingleMuon_Run2018C-UL2018"
            - "SingleMuon_Run2018D-UL2018"

event_selection:
    had_tau_pt: "> 30"
    had_tau_eta: "< 2.3"
    had_tau_decay_mode: ["0","1","10","11"] # has to be a list
    had_tau_id_vs_ele: "VVLoose"
    had_tau_id_vs_mu: "Tight"
    lep_iso: "< 0.15"

tree: "ntuple"
output_path: "/ceph/nshadskiy/FFmethod/test_v4"