tree: "ntuple"
file_path: "/ceph/nshadskiy/FFmethod/opt_test"
workdir_name: "opt_tests_full_v2"

era: "2018"
channel: "et" # options are et, mt, tt
target_process: 
    QCD: 
        SRlike_cuts:
            # cut on same/opposite sign of the tau pair.
            tau_pair_sign: "same" 
            # cut on the transverse mass of the muon/electron from the tau pair. 
            lep_mT: "< 50"
            # cut on extra leptons additional to the tau pair. 1 = no extra leptons, 0 = extra leptons
            no_extra_lep: True
            # cut on the tau ID vs Jets. One working point from VVVLoose to VVTight. Selecting events above the WP. 
            tau_id_vsJet: "Medium"
        ARlike_cuts:
            # cut on same/opposite sign of the tau pair.
            tau_pair_sign: "same" 
            # cut on the transverse mass of the muon/electron from the tau pair.
            lep_mT: "< 50" 
            # cut on extra leptons additional to the tau pair. 1 = no extra leptons, 0 = extra leptons
            no_extra_lep: True
            # cut on the tau ID vs Jets. Two working points from VVVLoose to VVTight. Selecting events between the WPs. 
            tau_id_vsJet: ["VVVLoose","Medium"]
        njet_split_categories: # at least one inclusive category needs to be defined
            - "== 0" 
            - "== 1"
            - ">= 2"
        #tau_pt_bins: [30,35,40,50,500] # for logx
        tau_pt_bins: [30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
        tau_pt_logx: False    
    Wjets: 
        SRlike_cuts:
            # cut on same/opposite sign of the tau pair.
            tau_pair_sign: "opposite" 
            # cut on number of b-tagged jets.
            nbtag: "== 0" 
            # cut on the transverse mass of the muon/electron from the tau pair. 
            lep_mT: "> 70"
            # cut on extra leptons additional to the tau pair. 1 = no extra leptons, 0 = extra leptons
            no_extra_lep: True
            # cut on the tau ID vs Jets. One working point from VVVLoose to VVTight. Selecting events above the WP. 
            tau_id_vsJet: "Medium"
        ARlike_cuts:
            # cut on same/opposite sign of the tau pair.
            tau_pair_sign: "opposite" 
            # cut on number of b-tagged jets.
            nbtag: "== 0"
            # cut on the transverse mass of the muon/electron from the tau pair.
            lep_mT: "> 70" 
            # cut on extra leptons additional to the tau pair. 1 = no extra leptons, 0 = extra leptons
            no_extra_lep: True
            # cut on the tau ID vs Jets. Two working points from VVVLoose to VVTight. Selecting events between the WPs. 
            tau_id_vsJet: ["VVVLoose","Medium"]
        njet_split_categories: # at least one inclusive category needs to be defined
            - "== 0" 
            - "== 1"
            - ">= 2"
        #tau_pt_bins: [30,34,38,50,60,75,90,110,500] # for logx
        tau_pt_bins: [30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
        tau_pt_logx: False
    ttbar: 
        SR_cuts:
            # cut on same/opposite sign of the tau pair.
            tau_pair_sign: "opposite"  
            # cut on number of b-tagged jets.
            nbtag: ">= 1" 
            # cut on extra leptons additional to the tau pair. 1 = no extra leptons, 0 = extra leptons
            no_extra_lep: True
            # cut on the tau ID vs Jets. One working point from VVVLoose to VVTight. Selecting events above the WP. 
            tau_id_vsJet: "Medium"
        AR_cuts:
            # cut on same/opposite sign of the tau pair.
            tau_pair_sign: "opposite"  
            # cut on number of b-tagged jets.
            nbtag: ">= 1"
            # cut on extra leptons additional to the tau pair. 1 = no extra leptons, 0 = extra leptons
            no_extra_lep: True
            # cut on the tau ID vs Jets. Two working points from VVVLoose to VVTight. Selecting events between the WPs. 
            tau_id_vsJet: ["VVVLoose","Medium"]
        SRlike_cuts:
            # cut on same/opposite sign of the tau pair.
            tau_pair_sign: "opposite" 
            # cut on number of b-tagged jets.
            nbtag: ">= 1" 
            # cut on extra leptons additional to the tau pair. 1 = no extra leptons, 0 = extra leptons
            no_extra_lep: False
            # cut on the tau ID vs Jets. One working point from VVVLoose to VVTight. Selecting events above the WP. 
            tau_id_vsJet: "Medium"
        ARlike_cuts:
            # cut on same/opposite sign of the tau pair.
            tau_pair_sign: "opposite" 
            # cut on number of b-tagged jets.
            nbtag: ">= 1"
            # cut on extra leptons additional to the tau pair. 1 = no extra leptons, 0 = extra leptons
            no_extra_lep: False
            # cut on the tau ID vs Jets. Two working points from VVVLoose to VVTight. Selecting events between the WPs. 
            tau_id_vsJet: ["VVVLoose","Medium"]
        njet_split_categories: # at least one inclusive category needs to be defined
            - "<= 1"
            - ">= 2"
        #tau_pt_bins: [30,32,35,40,45,70,100,170,500] # for logx
        tau_pt_bins: [30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]
        tau_pt_logx: False