tree: "ntuple"
file_path: "/ceph/nshadskiy/FFmethod/final_test_v1"

era: "2018"
channel: "et" # options are et, mt, tt
target_process: "QCD" # options are QCD, ttbar, Wjets
jet_split_categories:
    - "== 0" 
    - "== 1"
    - ">= 2"

workdir_name: "testing_v2"