channel: et
target_processes:
  QCD:
    split_categories:
      njets: ["==0", "==1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [40, 25, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.02) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.02) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    var_dependence: pt_2
    var_bins:
      "==0": [20.0, 20.54, 21.04, 21.57, 22.15, 22.64, 23.22, 23.76, 24.26, 24.78, 25.34, 25.92, 26.51, 27.12, 27.71, 28.29, 28.93, 29.54, 30.25, 30.92, 31.55, 32.21, 33.02, 33.75, 34.56, 35.32, 36.14, 36.99, 38.0, 39.06, 40.1, 41.45, 42.81, 44.33, 46.28, 48.44, 51.41, 54.83, 60.07, 68.4, 150.0]
      "==1": [20.0, 20.52, 21.14, 21.71, 22.34, 22.96, 23.66, 24.42, 25.18, 26.05, 26.98, 27.87, 28.83, 30.0, 31.18, 32.48, 34.1, 35.75, 37.88, 40.2, 43.19, 47.19, 52.64, 60.8, 75.31, 150.0]
      ">=2": [20.0, 21.67, 23.38, 25.49, 27.88, 30.68, 34.3, 39.11, 46.12, 60.07, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 10.0

  Wjets:
    split_categories:
      njets: ["==0", "==1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [40, 25, 10]

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    var_dependence: pt_2
    var_bins:
      "==0": [20.0, 20.35, 20.69, 21.04, 21.4, 21.78, 22.16, 22.56, 22.97, 23.4, 23.83, 24.28, 24.74, 25.21, 25.71, 26.22, 26.75, 27.3, 27.89, 28.49, 29.13, 29.79, 30.48, 31.21, 31.98, 32.83, 33.68, 34.64, 35.68, 36.84, 38.08, 39.45, 41.06, 42.85, 44.99, 47.6, 50.89, 55.43, 62.25, 74.98, 150.0]
      "==1": [20.0, 20.76, 21.54, 22.34, 23.18, 24.08, 25.01, 25.94, 26.94, 28.0, 29.14, 30.33, 31.55, 32.98, 34.45, 36.13, 37.94, 40.0, 42.4, 45.24, 48.63, 53.08, 58.9, 67.53, 83.24, 150.0]
      ">=2": [20.0, 22.34, 24.81, 27.61, 30.78, 34.62, 39.56, 45.89, 55.27, 72.21, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 10.0

  ttbar:
    split_categories:
      njets: ["<=1", ">=2"]
    split_categories_binedges:
      njets: [-0.5, 1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: [30, 30]

    SR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    AR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      nbtag: (nbtag >= 1)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    var_dependence: pt_2
    var_bins:
      "<=1": [20.0, 20.62, 21.01, 21.74, 22.38, 22.98, 23.81, 24.68, 25.42, 26.07, 26.67, 27.45, 28.29, 29.16, 30.05, 31.04, 32.08, 33.28, 34.4, 35.36, 37.11, 38.88, 40.74, 43.22, 46.78, 50.24, 53.84, 59.43, 67.81, 81.79, 150.0]
      ">=2": [20.0, 20.85, 21.68, 22.56, 23.57, 24.68, 25.87, 26.65, 27.78, 28.9, 30.28, 31.46, 32.6, 33.5, 34.72, 36.28, 38.0, 40.18, 41.93, 44.24, 46.8, 49.97, 52.57, 55.73, 60.23, 64.98, 69.14, 76.27, 86.95, 105.72, 150.0]
    # fit_option: ["poly_0", "poly_1", "poly_2", "poly_3"]
    fit_option: "smoothed"
    bandwidth: 10.0

process_fractions:
  processes: ["QCD", "Wjets", "ttbar_J"]

  split_categories:
    njets: ["==0", "==1", ">=2"]
  split_categories_binedges:
    njets: [-0.5, 0.5, 1.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      mt_1:
        min: 0.0
        max: 70.0
        rounding: 2
    var_dependence_n_bins: [40, 25, 10]

  SR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
  AR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    nbtag: (nbtag >= 0)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

  var_dependence: mt_1
  var_bins:
    "==0": [0.0, 2.38, 4.73, 7.06, 9.4, 11.7, 13.99, 16.23, 18.44, 20.61, 22.73, 24.8, 26.84, 28.82, 30.77, 32.67, 34.54, 36.33, 38.09, 39.81, 41.5, 43.16, 44.75, 46.32, 47.86, 49.37, 50.88, 52.35, 53.79, 55.23, 56.64, 58.02, 59.4, 60.76, 62.1, 63.42, 64.75, 66.07, 67.39, 68.7, 70.0]
    "==1": [0.0, 3.56, 7.05, 10.56, 14.0, 17.45, 20.77, 24.08, 27.31, 30.42, 33.47, 36.37, 39.22, 41.99, 44.68, 47.25, 49.78, 52.19, 54.6, 56.91, 59.17, 61.39, 63.57, 65.75, 67.87, 70.0]
    ">=2": [0.0, 8.59, 16.98, 25.02, 32.76, 39.85, 46.56, 52.78, 58.73, 64.42, 70.0]
