ntuple_path: "root://cmsdcache-kit-disk.gridka.de//store/user/jvoss/CROWN/ntuples/upart_17_09_26_sda_nom/CROWNRun"
# ntuple_path: "/ceph/jvoss/CROWN/ntuples/sda_v12_16_04_26_v2/CROWNRun"
# TODO: Include workdir name intp output and file path when doing preselection again!!! At smhtt_ul position !!!
output_path: /ceph/jvoss/FFmethod/upart_17_09_26_sda_nom_emb/

file_path: /ceph/jvoss/FFmethod/upart_17_09_26_sda_nom_emb/

workdir_name: ff_upart_17_09_26_sda_nom_emb

era: '2018'
tree: ntuple
nanoAOD_version: "nanoAOD_v15"
tau_vs_jet_wps:
  - Tight
  - Medium
  - VVVLoose
tau_vs_jet_wgt_wps:
  - Medium
  - Tight

use_embedding: true
use_center_of_mass_bins: true
