templates:
  split_schemes:
    2j:
      split_categories:
        n_jets: ["==0", ">=1"]
      split_categories_binedges:
        n_jets: [-0.5, 0.5, 22.5]
      correction_option:
        "==0": "smoothed"
        ">=1": "smoothed"
      bandwidth:
        "==0": 1.0
        ">=1": 1.0
    1j:
      split_categories:
        n_jets: [">=0"]
      split_categories_binedges:
        n_jets: [-0.5, 22.5]
      correction_option:
        ">=0": "smoothed"
      bandwidth:
        ">=0": 1
    QCD_jsplit: &QCD_jsplit
      split_categories:
        n_jets: [">=2"]
      split_categories_binedges:
        n_jets: [1.5, 22.5]
    Wjets_jsplit: &Wjets_jsplit
      split_categories:
        n_jets: [">=2"]
      split_categories_binedges:
        n_jets: [1.5, 22.5]
    ttbar_jsplit: &ttbar_jsplit
      split_categories:
        n_jets: ["==2", ">=3"]
      split_categories_binedges:
        n_jets: [1.5, 2.5, 23.5]
  var_dependence_n_bins:
    QCD:
      equipopulated_binning_options: &QCD_var_dependence_n_bins
        var_dependence_n_bins:
          ">=2": 8
    Wjets:
      equipopulated_binning_options: &Wjets_var_dependence_n_bins
        var_dependence_n_bins:
          ">=2": 8
    ttbar:
      equipopulated_binning_options: &ttbar_var_dependence_n_bins
        var_dependence_n_bins:
          "==2": 6
          ">=3": 8
  variables:
    deltaR_ditaupair:
      var_dependence: deltaR_ditaupair
      equipopulated_binning_options:
        variable_config:
          deltaR_ditaupair:
            min: 0.5
            max: 5.0
            rounding: 4
      correction_option: "smoothed"
    pt_tautau: &pt_tautau
      var_dependence: pt_tautau
      equipopulated_binning_options: &pt_tautau__eq_bin_opt
        variable_config:
          pt_tautau:
            min: 0.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 25.0
    pt_1: &pt_1
      var_dependence: pt_1
      equipopulated_binning_options: &pt_1__eq_bin_opt
        variable_config:
          pt_1:
            min: 32.0
            max: 120.0
            rounding: 2
      correction_option: "binwise#[0]+smoothed"
      bandwidth: 15.0
    jpt_1: &jpt_1
      var_dependence: jpt_1
      equipopulated_binning_options: &jpt_1__eq_bin_opt
        variable_config:
          jpt_1:
            min: 30.0
            max: 150.0
            rounding: 2
      correction_option: "smoothed"
    mass_1:
      var_dependence: mass_1
      equipopulated_binning_options:
        variable_config:
          mass_1:
            min: 0.0
            max: 1.0
            rounding: 4
      correction_option: "binwise"
      bandwidth: 0.1
    mass_2: &mass_2
      var_dependence: mass_2
      equipopulated_binning_options: &mass_2__eq_bin_opt
        variable_config:
          mass_2:
            min: 0.2
            max: 2.0
            rounding: 4
        add_left: [0.0]
      correction_option: "binwise#[0]+smoothed"
      bandwidth: 0.2
    iso_1: &iso_1
      var_dependence: iso_1
      equipopulated_binning_options: &iso_1__eq_bin_opt
        variable_config:
          iso_1:
            min: 0.00005
            max: 0.15
            rounding: 6
        add_left: [0.0]
      correction_option: "binwise#[0]+smoothed"
      bandwidth: 0.015
    tau_decaymode_2: &tau_decaymode_2
      var_dependence: tau_decaymode_2
      correction_option: "binwise"
      bandwidth: 1.0
    mt_1:
      var_dependence: mt_1
      equipopulated_binning_options:
        variable_config:
          mt_1:
            min: 0.0
            max: 150.0
            rounding: 6
        add_left: [0.0]
      correction_option: "binwise#[0]+smoothed"
      bandwidth: 15.0
    m_vis:
      var_dependence: m_vis
      equipopulated_binning_options:
        variable_config:
          m_vis:
            min: 10.0
            max: 250.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 25.0
    met: &met
      var_dependence: met
      equipopulated_binning_options: &met__eq_bin_opt
        variable_config:
          met:
            min: 0.0
            max: 130.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 25.0
    mt_tot: &mt_tot
      var_dependence: mt_tot
      equipopulated_binning_options: &mt_tot__eq_bin_opt
        variable_config:
          mt_tot:
            min: 0.0
            max: 250.0
            rounding: 2
      correction_option: "smoothed"
      bandwidth: 25.0


channel: mt
target_processes:
  QCD:
    chain_DR_SR_to_non_closure: true
    non_closure:
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *QCD_jsplit]
        var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
      pt_1:
        <<: [*pt_1, *QCD_jsplit]
        equipopulated_binning_options:
          <<: [*pt_1__eq_bin_opt, *QCD_var_dependence_n_bins]
          var_dependence_n_bins:
            ">=2": 6
        bandwidth:
          ">=2": 30.0
        var_bins:
          ">=2": [32.0, 36.28, 41.52, 49.02, 59.75, 76.2, 120.0]
      jpt_1:
        <<: [*jpt_1, *QCD_jsplit]
        equipopulated_binning_options:
          <<: [*jpt_1__eq_bin_opt, *QCD_var_dependence_n_bins]
          var_dependence_n_bins:
            ">=2": 8
        bandwidth: [50.0]
        var_bins:
          ">=2": [30.0, 43.61, 53.05, 61.9, 72.26, 83.42, 98.1, 118.52, 150.0]
      met:
        <<: [*met, *QCD_jsplit]
        equipopulated_binning_options:
          <<: [*met__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth:
          ">=2": 40
        var_bins:
          ">=2": [0.0, 12.85, 20.01, 27.48, 35.58, 45.71, 58.81, 80.1, 130.0]
      mt_tot:
        <<: [*mt_tot, *QCD_jsplit]
        equipopulated_binning_options:
          <<: [*mt_tot__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth:
          ">=2": 50.0
        var_bins:
          ">=2": [0.0, 53.81, 72.81, 86.11, 98.67, 112.88, 130.65, 157.81, 250.0]
      mass_2:
        <<: [*mass_2, *QCD_jsplit]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *QCD_var_dependence_n_bins]
        bandwidth:
          ">=2": 0.3
        var_bins:
          ">=2": [0.0, 0.2, 0.5483, 0.7031, 0.8369, 0.9468, 1.0645, 1.1865, 1.3359, 2.0]
      iso_1:
        <<: [*iso_1, *QCD_jsplit]
        equipopulated_binning_options:
          <<: [*iso_1__eq_bin_opt, *QCD_var_dependence_n_bins]
          var_dependence_n_bins:
            ">=2": 8
        # correction_option: "binwise#[0]+smoothed"
        correction_option: "binwise"
        bandwidth:
          ">=2": 0.08
        var_bins:
          ">=2": [0.0, 0.00005, 0.009049, 0.01609, 0.025246, 0.037576, 0.055187, 0.075584, 0.106164, 0.15]

    DR_SR:
      use_embedding: false
      use_orthogonal_fake_factors: true
      compute_orthogonal_fake_factors_using_data: true
      <<: [*pt_tautau, *QCD_jsplit]
      equipopulated_binning_options:
        <<: [*pt_tautau__eq_bin_opt, *QCD_var_dependence_n_bins]
      correction_option: "binwise#[-1]+smoothed"
      bandwidth:
        ">=2": 25
      var_bins:
        ">=2": [0.0, 29.85, 45.64, 59.12, 72.92, 86.63, 101.85, 120.21, 150.0]

      SRlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 < 50)
        n_bjets: (n_bjets >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      ARlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
        lep_mt: (mt_1 < 50)
        n_bjets: (n_bjets >= 0)
        tau_pair_sign: ((q_1*q_2) > 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"
      AR_SR_cuts:
        lep_mt: (mt_1 < 70)
        n_bjets: (n_bjets >= 0)
        tau_pair_sign: ((q_1*q_2) < 0)
        lep_iso: "(!((iso_1 >= 0.05) && (iso_1 <= 0.15)))"

      non_closure:
        tau_decaymode_2:
          <<: [*tau_decaymode_2, *QCD_jsplit]
          var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
  # Wjets:
  #   chain_DR_SR_to_non_closure: true
  #   non_closure:
  #     tau_decaymode_2:
  #       <<: [*tau_decaymode_2, *Wjets_jsplit]
  #       var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
  #     pt_1:
  #       <<: [*pt_1, *Wjets_jsplit]
  #       equipopulated_binning_options:
  #         <<: [*pt_1__eq_bin_opt, *Wjets_var_dependence_n_bins]
  #         var_dependence_n_bins:
  #           ">=2": 8
  #       bandwidth:
  #         ">=2": 15.0
  #       var_bins:
  #         ">=2": [32.0, 37.68, 43.39, 49.71, 57.03, 65.78, 77.16, 93.27, 120.0]
  #     jpt_1:
  #       <<: [*jpt_1, *Wjets_jsplit]
  #       equipopulated_binning_options:
  #         <<: [*jpt_1__eq_bin_opt, *Wjets_var_dependence_n_bins]
  #         var_dependence_n_bins:
  #           ">=2": 7
  #       bandwidth: [30.0]
  #       var_bins:
  #         ">=2": [30.0, 45.51, 55.47, 65.94, 78.09, 93.44, 114.76, 150.0]
  #     met:
  #       <<: [*met, *Wjets_jsplit]
  #       equipopulated_binning_options:
  #         <<: [*met__eq_bin_opt, *Wjets_var_dependence_n_bins]
  #       bandwidth:
  #         ">=2": 15.0
  #       var_bins:
  #         ">=2": [0.0, 33.45, 43.15, 50.91, 59.19, 68.71, 80.6, 97.8, 130.0]
  #     mt_tot:
  #       <<: [*mt_tot, *Wjets_jsplit]
  #       equipopulated_binning_options:
  #         <<: [*mt_tot__eq_bin_opt, *Wjets_var_dependence_n_bins]
  #       correction_option: "smoothed"
  #       bandwidth:
  #         ">=2": 10.0
  #       var_bins:
  #         ">=2": [0.0, 110.56, 123.71, 134.66, 146.45, 160.47, 176.79, 201.19, 250.0]
  #     mass_2:
  #       <<: [*mass_2, *Wjets_jsplit]
  #       equipopulated_binning_options:
  #         <<: [*mass_2__eq_bin_opt, *Wjets_var_dependence_n_bins]
  #         var_dependence_n_bins:
  #           ">=2": 8
  #       correction_option: "binwise#[0]+smoothed"
  #       bandwidth:
  #         ">=2": 0.3
  #       var_bins:
  #         ">=2": [0.0, 0.2, 0.5605, 0.6978, 0.811, 0.9229, 1.04, 1.1621, 1.3027, 2.0]
  #     iso_1:
  #       <<: [*iso_1, *Wjets_jsplit]
  #       equipopulated_binning_options:
  #         <<: [*iso_1__eq_bin_opt, *Wjets_var_dependence_n_bins]
  #         var_dependence_n_bins:
  #           ">=2": 8
  #       correction_option: "binwise#[0]+smoothed"
  #       bandwidth:
  #         ">=2": 0.04
  #       var_bins:
  #         ">=2": [0.0, 0.00005, 0.006097, 0.010535, 0.015964, 0.023284, 0.033427, 0.048621, 0.074165, 0.15]

  #   DR_SR:
  #     use_embedding: false
  #     use_orthogonal_fake_factors: true
  #     compute_orthogonal_fake_factors_using_data: false
  #     <<: [*pt_tautau, *Wjets_jsplit]
  #     equipopulated_binning_options:
  #       <<: [*pt_tautau__eq_bin_opt, *Wjets_var_dependence_n_bins]
  #       var_dependence_n_bins:
  #         ">=2": 1
  #     bandwidth:
  #       ">=2": 25.0
  #     var_bins:
  #       ">=2": [0.0, 150.0]
  #     SRlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
  #       lep_mt: (mt_1 > 0)
  #       n_bjets: (n_bjets == 0)
  #       tau_pair_sign: ((q_1*q_2) < 0)
  #       lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
  #     ARlike_cuts: # Try for yet perpendicular to the fake_factors_mt.yaml definition!
  #       lep_mt: (mt_1 > 0)
  #       n_bjets: (n_bjets == 0)
  #       tau_pair_sign: ((q_1*q_2) < 0)
  #       lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
  #     AR_SR_cuts:
  #       lep_mt: (mt_1 < 70)
  #       n_bjets: (n_bjets >= 0)
  #       tau_pair_sign: ((q_1*q_2) < 0)
  #       lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))

  #     non_closure:
  #       tau_decaymode_2:
  #         <<: [*tau_decaymode_2, *Wjets_jsplit]
  #         var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
  ttbar:
    non_closure:
      tau_decaymode_2:
        <<: [*tau_decaymode_2, *ttbar_jsplit]
        var_bins: [-0.5, 0.5, 9.5, 10.5, 11.5]
      pt_1:
        <<: [*pt_1, *ttbar_jsplit]
        equipopulated_binning_options:
          <<: [*pt_1__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "==2": 30
          ">=3": 30
        var_bins:
          "==2": [32.0, 38.47, 46.24, 55.11, 66.76, 83.24, 120.0]
          ">=3": [32.0, 37.31, 42.96, 49.0, 55.75, 64.14, 74.71, 90.17, 120.0]
      jpt_1:
        <<: [*jpt_1, *ttbar_jsplit]
        equipopulated_binning_options:
          <<: [*jpt_1__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "==2": 20.0
          ">=3": 20.0
        var_bins:
          "==2": [30.0, 49.34, 61.53, 73.82, 87.31, 106.17, 150.0]
          ">=3": [30.0, 57.64, 68.51, 78.32, 88.63, 99.02, 111.88, 127.82, 150.0]
      met:
        <<: [*met, *ttbar_jsplit]
        equipopulated_binning_options:
          <<: [*met__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "==2": 30.0
          ">=3": 25.0
        var_bins:
          "==2": [0.0, 29.4, 44.35, 58.2, 73.32, 93.37, 130.0]
          ">=3": [0.0, 26.7, 39.15, 50.28, 61.26, 73.0, 87.06, 104.52, 130.0]
      mt_tot:
        <<: [*mt_tot, *ttbar_jsplit]
        equipopulated_binning_options:
          <<: [*mt_tot__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "==2": 30.0
          ">=3": 25.0
        var_bins:
          "==2": [0.0, 97.55, 120.62, 139.62, 158.83, 187.11, 250.0]
          ">=3": [0.0, 89.59, 110.01, 125.19, 139.91, 155.13, 173.56, 198.42, 250.0]
      mass_2:
        <<: [*mass_2, *ttbar_jsplit]
        equipopulated_binning_options:
          <<: [*mass_2__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "==2": 0.2
          ">=3": 0.15
        var_bins:
          "==2": [0.0, 0.2, 0.6309, 0.8228, 0.9814, 1.126, 1.3066, 2.0]
          ">=3": [0.0, 0.2, 0.5498, 0.7056, 0.8301, 0.936, 1.0469, 1.1787, 1.3291, 2.0]
      iso_1:
        <<: [*iso_1, *ttbar_jsplit]
        equipopulated_binning_options:
          <<: [*iso_1__eq_bin_opt, *ttbar_var_dependence_n_bins]
        bandwidth:
          "==2": 0.03
          ">=3": 0.03
        var_bins:
          "==2": [0.0, 0.00005, 0.007391, 0.013446, 0.021728, 0.034618, 0.061761, 0.15]
          ">=3": [0.0, 0.00005, 0.006266, 0.010457, 0.01553, 0.022521, 0.031821, 0.045844, 0.072362, 0.15]
