channel: tt
target_processes:
  QCD:
    split_categories:
      njets: [">=2"]
    split_categories_binedges:
      njets: [1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_1:
          min: 40.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: 6

    SRlike_cuts:
      had_tau_id_vs_jet_1: id_tau_vsJet_Medium_1 > 0.5
      had_tau_id_vs_jet_2: id_tau_vsJet_Medium_2 > 0.5
      jj_selection: "njets >= 2 && jpt_1>=20 && jpt_2>=20 && jj_deltaR >= 0.4"
      # -------------------------------------------
      tau_pair_sign: (q_1*q_2) > 0
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet_1: (id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)
      had_tau_id_vs_jet_2: id_tau_vsJet_Medium_2 > 0.5
      jj_selection: "njets >= 2 && jpt_1>=20 && jpt_2>=20 && jj_deltaR >= 0.4"
      # -------------------------------------------
      tau_pair_sign: (q_1*q_2) > 0
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    var_dependence: pt_1
    var_bins:
      ">=2": [40.0, 49.95, 56.5, 64.33, 75.37, 92.07, 150.0]
    fit_option:
      ">=2": "smoothed" #["poly_0", "poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]
    bandwidth:
      ">=2": 12.0

  QCD_subleading:
    split_categories:
      njets: [">=2"]
    split_categories_binedges:
      njets: [1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 40.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: 6

    SRlike_cuts:
      had_tau_id_vs_jet_1: id_tau_vsJet_Medium_1 > 0.5
      had_tau_id_vs_jet_2: id_tau_vsJet_Medium_2 > 0.5
      jj_selection: "njets >= 2 && jpt_1>=20 && jpt_2>=20 && jj_deltaR >= 0.4"
      # -------------------------------------------
      tau_pair_sign: (q_1*q_2) > 0
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet_1: id_tau_vsJet_Medium_1 > 0.5
      had_tau_id_vs_jet_2: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      jj_selection: "njets >= 2 && jpt_1>=20 && jpt_2>=20 && jj_deltaR >= 0.4"
      # -------------------------------------------
      tau_pair_sign: (q_1*q_2) > 0
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)

    var_dependence: pt_2
    var_bins:
      ">=2": [40.0, 41.95, 44.2, 46.98, 51.18, 58.89, 150.0]
    fit_option:
      ">=2": "smoothed" #["poly_0", "poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]
    bandwidth:
      ">=2": 15.0

  ttbar:
    split_categories:
      njets: ["==2", ">=3"]
    split_categories_binedges:
      njets: [1.5, 2.5, 23.5]
    equipopulated_binning_options:
      variable_config:
        pt_1:
          min: 40.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins:
        "==2": 3
        ">=3": 4

    SR_cuts:
      tau_pair_sign: "(q_1*q_2) < 0"
      no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
      had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
      had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

    AR_cuts:
      tau_pair_sign: "(q_1*q_2) < 0"
      no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
      had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
      had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

    SRlike_cuts:
      tau_pair_sign: "(q_1*q_2) < 0"
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
      had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
      had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

    ARlike_cuts:
      tau_pair_sign: "(q_1*q_2) < 0"
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
      had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
      had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

    var_dependence: "pt_1"
    var_bins:
      "==2": [40.0, 60.78, 81.71, 150.0]
      ">=3": [40.0, 56.57, 69.07, 89.77, 150.0]
    fit_option:
      "==2": "smoothed" #["poly_0", "poly_1", "poly_2", "poly_4"]
      ">=3": "smoothed" #["poly_0", "poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]
    bandwidth:
      "==2": 12.0
      ">=3": 12.0

  ttbar_subleading:
    split_categories:
      njets: ["==2", ">=3"]
    split_categories_binedges:
      njets: [1.5, 2.5, 23.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 40.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins:
        "==2": 3
        ">=3": 4

    SR_cuts:
      tau_pair_sign: "(q_1*q_2) < 0"
      no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
      had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
      had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

    AR_cuts:
      tau_pair_sign: "(q_1*q_2) < 0"
      no_extra_lep: "(extramuon_veto < 0.5) && (extraelec_veto < 0.5)"
      had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
      had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

    SRlike_cuts:
      tau_pair_sign: "(q_1*q_2) < 0"
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
      had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
      had_tau_id_vs_jet_2: "id_tau_vsJet_Medium_2 > 0.5"
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

    ARlike_cuts:
      tau_pair_sign: "(q_1*q_2) < 0"
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5))"
      had_tau_id_vs_jet_1: "id_tau_vsJet_Medium_1 > 0.5"
      had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
    var_dependence: "pt_2"
    var_bins:
      "==2": [40.0, 45.09, 53.97, 150.0]
      ">=3": [40.0, 44.0, 49.44, 59.23, 150.0]
    fit_option:
      "==2": "smoothed" #["poly_0", "poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]
      ">=3": "smoothed" #["poly_0", "poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]
    bandwidth:
      "==2": 12.0
      ">=3": 12.0

process_fractions:
  processes: ["QCD", "ttbar_J"]

  split_categories:
    njets: ["<=1", ">=2"]
  split_categories_binedges:
    njets: [-0.5, 1.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      m_vis:
        min: 15.0
        max: 200.0
        rounding: 2
    var_dependence_n_bins:
      "<=1": 9
      ">=2": 20

  SR_cuts:
    had_tau_id_vs_jet_1: id_tau_vsJet_Medium_1 > 0.5
    had_tau_id_vs_jet_2: id_tau_vsJet_Medium_2 > 0.5
    # -------------------------------------------
    tau_pair_sign: (q_1*q_2) < 0
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)
    bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

  AR_cuts:
    had_tau_id_vs_jet_1: (id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)
    had_tau_id_vs_jet_2: id_tau_vsJet_Medium_2 < 0.5
    # -------------------------------------------
    tau_pair_sign: (q_1*q_2) < 0
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto < 0.5)
    bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

  var_dependence: m_vis
  var_bins:
    "<=1": [15.0, 68.4, 89.87, 100.37, 110.48, 121.43, 134.31, 149.49, 169.25, 200.0]
    ">=2": [15.0, 37.9, 48.59, 59.28, 68.85, 78.34, 85.98, 92.23, 97.84, 103.03, 108.23, 113.95, 119.79, 126.3, 133.01, 140.36, 148.63, 157.94, 169.26, 183.57, 200.0]

process_fractions_subleading:
  processes: ["QCD", "ttbar_J"]

  split_categories:
    njets: ["<=1", ">=2"]
  split_categories_binedges:
    njets: [-0.5, 1.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      m_vis:
        min: 15.0
        max: 200.0
        rounding: 2
    var_dependence_n_bins:
      "<=1": 9
      ">=2": 20

  SR_cuts:
    had_tau_id_vs_jet_1: id_tau_vsJet_Medium_1 > 0.5
    had_tau_id_vs_jet_2: id_tau_vsJet_Medium_2 > 0.5
    # -------------------------------------------
    tau_pair_sign: (q_1*q_2) < 0
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5)
    bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

  AR_cuts:
    had_tau_id_vs_jet_1: id_tau_vsJet_Medium_1 < 0.5
    had_tau_id_vs_jet_2: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
    # -------------------------------------------
    tau_pair_sign: (q_1*q_2) < 0
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5)
    bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

  var_dependence: m_vis
  var_bins:
    "<=1": [15.0, 68.4, 89.87, 100.37, 110.48, 121.43, 134.31, 149.49, 169.25, 200.0]
    ">=2": [15.0, 37.91, 48.59, 59.29, 68.86, 78.34, 85.98, 92.24, 97.84, 103.03, 108.23, 113.95, 119.8, 126.31, 133.01, 140.36, 148.63, 157.94, 169.26, 183.57, 200.0]
