channel: et
target_processes:
  QCD:
    split_categories:
      n_jets: [">=2"]
    split_categories_binedges:
      n_jets: [1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: 4

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      n_bjets: (n_bjets >= 0)
      jj_selection: "n_jets >= 2 && jpt_1>=20 && jpt_2>=20 && jj_deltaR > 0.4"
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.00) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      n_bjets: (n_bjets >= 0)
      jj_selection: "n_jets >= 2 && jpt_1>=20 && jpt_2>=20 && jj_deltaR > 0.4"
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.00) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    var_dependence: pt_2
    var_bins:
      ">=2": [20.0, 34.7, 41.9, 54.56, 150.0]
    fit_option:
      ">=2": "smoothed"

  # Wjets:
  #   split_categories:
  #     n_jets: [">=2"]
  #   split_categories_binedges:
  #     n_jets: [1.5, 22.5]
  #   equipopulated_binning_options:
  #     variable_config:
  #       pt_2:
  #         min: 30.0
  #         max: 150.0
  #         rounding: 2
  #     var_dependence_n_bins:
  #       ">=2": 1

  #   SRlike_cuts:
  #     had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
  #     # -------------------------------------------
  #     lep_mt: (mt_1 >= 70)
  #     n_bjets: (n_bjets == 0)
  #     tau_pair_sign: ((q_1*q_2) < 0)
  #     lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
  #     # -------------------------------------------
  #     no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
  #   ARlike_cuts:
  #     had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
  #     # -------------------------------------------
  #     lep_mt: (mt_1 >= 70)
  #     n_bjets: (n_bjets == 0)
  #     tau_pair_sign: ((q_1*q_2) < 0)
  #     lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
  #     # -------------------------------------------
  #     no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

  #   var_dependence: pt_2
  #   var_bins:
  #     ">=2": [30.0, 150.0]
  #   fit_option:
  #     ">=2": "binwise" #["poly_0", "poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]
  #   bandwidth:
  #     ">=2": 12.0

  ttbar:
    split_categories:
      n_jets: ["==2", ">=3"]
    split_categories_binedges:
      n_jets: [1.5, 2.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins:
        "==2": 8
        ">=3": 10

    SR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      # lep_mt: (mt_1 < 70)
      bb_selection: "n_bjets >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    AR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      bb_selection: "n_bjets >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      # lep_mt: (mt_1 < 70)
      bb_selection: "n_bjets >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      # lep_mt: (mt_1 < 70)
      bb_selection: "n_bjets >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    var_dependence: pt_2
    var_bins:
      "==2": [20.0, 32.58, 35.33, 38.91, 43.42, 49.0, 57.78, 75.19, 150.0]
      ">=3": [20.0, 31.76, 34.05, 36.4, 39.38, 43.09, 48.0, 54.75, 64.68, 84.09, 150.0]
    fit_option: "smoothed" #["poly_0", "poly_1", "poly_2"]

process_fractions:
  processes: ["QCD", "ttbar_J"]

  split_categories:
    n_jets: ["<=2", ">=3"]
  split_categories_binedges:
    n_jets: [-0.5, 1.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      mt_1:
        min: 0.0
        max: 70.0
        rounding: 2
    var_dependence_n_bins:
      ">=3": 3
      "<=2": 2

  SR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
    bb_selection: "n_bjets >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
  AR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
    bb_selection: "n_bjets >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

  var_dependence: mt_1
  var_bins:
    "<=2": [0.0, 41.06, 70.0]
    ">=3": [0.0, 28.6, 51.46, 70.0]
