channel: et
target_processes:
  QCD:
    split_categories:
      njets: [">=2"]
    split_categories_binedges:
      njets: [1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins: 4

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      jj_selection: "njets >= 2 && jpt_1>=20 && jpt_2>=20 && jj_deltaR > 0.4"
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.00) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 50)
      nbtag: (nbtag >= 0)
      jj_selection: "njets >= 2 && jpt_1>=20 && jpt_2>=20 && jj_deltaR > 0.4"
      tau_pair_sign: ((q_1*q_2) > 0)
      lep_iso: ((iso_1 >= 0.00) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    var_dependence: pt_2
    var_bins:
      ">=2": [20.0, 24.28, 30.85, 42.39, 150.0]
    fit_option:
      ">=2": "smoothed"

  Wjets:
    split_categories:
      njets: [">=2"]
    split_categories_binedges:
      njets: [1.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 30.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins:
        ">=2": 5

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 >= 70)
      nbtag: (nbtag == 0)
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    var_dependence: pt_2
    var_bins:
      ">=2": [30.0, 34.65, 41.07, 51.07, 70.35, 150.0]
    fit_option:
      ">=2": "smoothed" #["poly_0", "poly_1", "poly_2", "poly_3", "poly_4", "poly_5"]
    bandwidth:
      ">=2": 12.0

  ttbar:
    split_categories:
      njets: ["==2", ">=3"]
    split_categories_binedges:
      njets: [1.5, 2.5, 22.5]
    equipopulated_binning_options:
      variable_config:
        pt_2:
          min: 20.0
          max: 150.0
          rounding: 2
      var_dependence_n_bins:
        "==2": 5
        ">=3": 8

    SR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    AR_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)

    SRlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    ARlike_cuts:
      had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
      # -------------------------------------------
      lep_mt: (mt_1 < 70)
      bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
      tau_pair_sign: ((q_1*q_2) < 0)
      lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
      # -------------------------------------------
      no_extra_lep: "!((extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5))"

    var_dependence: pt_2
    var_bins:
      "==2": [20.0, 25.99, 32.83, 42.19, 58.02, 150.0]
      ">=3": [20.0, 23.11, 26.51, 30.23, 34.78, 40.72, 48.91, 64.61, 150.0]
    fit_option: "smoothed" #["poly_0", "poly_1", "poly_2"]

process_fractions:
  processes: ["QCD", "Wjets", "ttbar_J"]

  split_categories:
    njets: ["<=1", ">=2"]
  split_categories_binedges:
    njets: [-0.5, 1.5, 22.5]
  equipopulated_binning_options:
    variable_config:
      mt_1:
        min: 0.0
        max: 70.0
        rounding: 2
    var_dependence_n_bins:
      "<=1": 9
      ">=2": 25

  SR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_Medium_2 > 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
    bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"
  AR_cuts:
    had_tau_id_vs_jet: (id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)
    # -------------------------------------------
    lep_mt: (mt_1 < 70)
    tau_pair_sign: ((q_1*q_2) < 0)
    lep_iso: ((iso_1 >= 0.0) && (iso_1 <= 0.15))
    # -------------------------------------------
    no_extra_lep: (extramuon_veto < 0.5) && (extraelec_veto < 0.5) && (dilepton_veto< 0.5)
    bb_selection: "nbtag >= 1 && bpair_pt_1>=20 && bpair_pt_2>=20"

  var_dependence: mt_1
  var_bins:
    "<=1": [0.0, 9.41, 19.45, 28.54, 36.64, 44.52, 51.45, 57.92, 63.98, 70.0]
    ">=2": [0.0, 3.55, 7.08, 10.72, 14.15, 17.58, 20.99, 24.3, 27.55, 30.69, 33.74, 36.64, 39.51, 42.29, 44.86, 47.52, 50.07, 52.46, 54.8, 57.14, 59.36, 61.59, 63.8, 65.91, 67.97, 70.0]
